### ISSUE TITLE
Expose a z-index init option for the login modal

### ISSUE THREAD

**Issue by Adamj1232** [Web3Auth/web3auth-web#1018]
### **Is your feature request related to a problem? Please describe.**

A config option to set the z-index of the login modal.
Blocknative's web3-onboard which supports web3-auth requires a z-index setter to allow proper layering of modals within the library.

### **Describe the solution you'd like**

A z-index initialization prop for the modal

### **Describe alternatives you've considered**

We are currently using the "hack-y" approach of:
```
const subscribeAuthEvents = (web3auth: Web3Auth) => {
        // emitted when modal visibility changes.
        web3auth.on(LOGIN_MODAL_EVENTS.MODAL_VISIBILITY, isVisible => {
          if (isVisible) {
            // Move to bottom of stack
            setTimeout(() => {
              const modal = document.getElementById('w3a-modal')
              if (modal) {
                modal.style.zIndex = '50'
              }
            }, 10)
          }
        })
```

**Comment by chaitanyapotti** [comment]
This is supported with 4.0.0
