### ISSUE TITLE
Can't we build a simple html/js web3 auth project anymore? The demo example for htm/js doesn't exisit anymore 

### ISSUE THREAD

**Issue by rakshith333** [Web3Auth/web3auth-web#1040]

**Comment by rakshith333** [comment]
I was building a simple web3 auth interface for a website and i was referring to html/js demo example. But it has been removed recently because of the major changes in codebase. Please share the link to simple web3 auth template if anyone of you have it

**Comment by chaitanyapotti** [comment]
It's moved to https://github.com/web3auth/examples
