### ISSUE TITLE
What's the difference here?

### ISSUE THREAD

**Issue by Deveshb15** [Web3Auth/web3auth-web#1044]
I installed and ran this setup locally -> https://github.com/Web3Auth/web3auth-web/tree/master/demo/custom-ui-react-app

I even installed tkey(self host) locally and was wondering what is the difference between the two of these?

**Comment by Deveshb15** [comment]
is it that web3auth plug n play has provider which can be used with ethers.js while tkey does not?

**Comment by shahbaz17** [comment]
Hey @Deveshb15 

Most of the examples you tried from that repo are moved into [this examples repo](https://github.com/web3Auth/examples).

To answer your questions, first, the custom-ui-react-app is an example of our Plug & Play Core SDK, where you could use your own UI for the login modal compared to what you get default from Plug & Play Modal SDK. Upon initiating the login request, it goes to app.openlogin.com or beta.openlogin.com, depending upon your web3auth network.

Second, tKey(Self Host) is where you get to own the overall experience. The login screen, to openlogin redirect screen, etc. Also, you get to decide the Shares of tKey. Read more about it https://web3auth.io/docs/sdk/self-host/
