### ISSUE TITLE
external wallet authenticateUser cors error

### ISSUE THREAD

**Issue by Domino9697** [Web3Auth/web3auth-web#1054]
### **Describe the bug**

When the using the authenticateUser method of web3auth with an external wallet (Metamask), the web3auth library makes a request to `https://authjs.web3auth.io/siww/verify`. The request fails with a cors error because the `mainnet` header is not authorized to be set.

![image](https://user-images.githubusercontent.com/31185922/207015877-1ca5b0c0-d46b-4592-944c-0b0344cbcc20.png)

I checked the which headers were authorized. Here is the list coming from the server:
![image](https://user-images.githubusercontent.com/31185922/207016762-5bf76cb1-7849-4b59-9dd7-c6608e40bb2a.png)

I guess the network header is just missing ?

### **To Reproduce**

1. Clone the following project: https://github.com/Domino9697/web3auth-repro
2. Create a Web3auth project
3. Add a .env file with your client id: NEXT_PUBLIC_WEB3_AUTH_CLIENT_ID
 4. Run the project
 5. Click on login and log in with metamask
 6. Cors error appears

### **Expected behavior**

The verify request does not fail with a cors error and returns the client ID token.

### **Screenshots**

Screenshots of console logs are welcome

### **Device Info (please complete the following information):**

- OS: Linux
- Browser [e.g. chrome, safari]: Chrome
- Version [e.g. 22]: 108.0.5359.98
- Web3Auth Version [e.g. 1.0.0]: 4.0.0-alpha.0

**Comment by ma68546** [comment]
Hi there, we are trying the exact same thing. It seems that the "network" header is missing 🙈

**Comment by chaitanyapotti** [comment]
This is fixed in 4.0.0. Please update
