### ISSUE TITLE
Support for more Solana wallets (Wallet Adapter Standard, Glow, etc)

### ISSUE THREAD

**Issue by AnishDe12020** [Web3Auth/web3auth-web#1128]
### **Is your feature request related to a problem? Please describe.**

When connecting with an external wallet on the Solana chain, currently only Phantom is supported. May users use other wallets as well like Solflare, Glow, Backpack, etc.

### **Describe the solution you'd like**

Support for more wallet adapters like  Glow, and wallets which follow the [Wallet Adapter Standard](https://github.com/solana-labs/wallet-standard) (e.g. Backpack)

### **Describe alternatives you've considered**

None

**Comment by shahbaz17** [comment]
Hey @AnishDe12020 

Thank you for sharing your feature request. To answer your question, We support more Solana external wallets than just Phantom. The supported external wallets are:
* [Torus Solana Wallet](https://web3auth.io/docs/sdk/web/adapters/torus-solana)
* [Slope](https://web3auth.io/docs/sdk/web/adapters/slope)
* [Solflare](https://web3auth.io/docs/sdk/web/adapters/solflare)
* [Phantom](https://web3auth.io/docs/sdk/web/adapters/phantom)

Are you looking for any specific wallets? Like Glow or Backpack? Or if you have a list, would love to see that 😄😍

**Comment by AnishDe12020** [comment]
Came across solflare support after posting the issue and that's awesome! Although, I think I need to install the solflare adapter and add it as an adapter explicitly, it is not there by default.

Btw, I am looking forward to web3auth supporting Glow & Backpack (which uses the wallet adapter standard so supporting that should be sufficient in theory)

**Comment by shahbaz17** [comment]
Yes, that's correct, solflare is not default. Also, kept a note for Glow & Backpack to be included in the supported wallet adapter's list.
