### ISSUE TITLE
Yaoo.com, Hotmail.com, Outlook.com and Other Domains not Getting Email Verification. 

### ISSUE THREAD

**Issue by metasoul111** [Web3Auth/web3auth-web#1157]
This issue has happend to many of our users, they go to log in, enter their email address and wait for the email verification to come and it never does. We have asked them to check their spam, junk folders and also wait some time for the email to arrive. 

This happens with Yahoo.com 100% of the time, Hotmail and Outlook 50% of the time and other domains such as t-online.de

### **To Reproduce**

1. Attempt to sign in using Yahoo.com email address
2. Wait for email to come

### **Expected behavior**

The user should get the email verification 

### **Screenshots**

N/A

### **Device Info (please complete the following information):**

- Device: 
- OS: Windows 10
- Browser Chrome
- Version 
10.8.168
 Web3Auth Version 3.3.0

### **Additional context**

N/A

**Comment by minamisouju** [comment]
@metasoul111 
Hi, I am facing same problem now. have you resolved this issue? if so, can you share me how?

**Comment by fimak** [comment]
It is still happening with Yahoo domain. Can someone investigate it?
