### ISSUE TITLE
Sorry, the Torus Network that powers Web3Auth is currently very busy.

### ISSUE THREAD

**Issue by designbyfaizi** [Web3Auth/web3auth-web#1172]
### I am getting the error described in the title in torusSdk.getRedirectresult() function.

I am using Torus custom auth to implement login in my app. I use the triggerLogin() function to redirect my page to the auth0 login page where the user enters his email and logs in using his OTP. After entering the OTP, I am redirected back to my app where I fetch the result of the redirect using getRedirectResult() function. The problem is that once every 4 or 5 times, It gives me the error message that says 
'Sorry, the Torus Network that powers Web3Auth is currently very busy. We will generate your key in time. Pls try again later.' 

I am guessing that this error has got to do something with the torus servers having too much traffic. Maybe this is an issue with Torus Custom Auth only and has been patched in Web3Auth. If anyone can help me solve this issue, that would be great.

### Steps to Reproduce

This error occurs completely randomly without any apparent reason, so it is difficult to reproduce. Still the steps are as follows:

1. Initialize TorusSDK
2. Call the triggerLogin function.
3. Complete the login process.
4. After redirect catch the error on getRedirectResult function.

### Expected behavior

Expected and normal behavior is that it should redirect back to my app and should provide the walletData. In case of any error or exception it should return with the error. it is throwing Error but the reason that happens is not clear to me.

### Screenshots
![Web3 Error 2](https://user-images.githubusercontent.com/49490561/210941128-830ff641-06f3-49e6-b77d-c1e9ce54d7b3.png)

### Device Info (please complete the following information):

- Device: Lenovo Thinkpad T470
- OS: Kubuntu
- Browser Brave
- Version [Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)](https://brave.com/latest/)
- Web3Auth Version 2.1.3
- Torus Custom Auth Version 9.1.0

**Comment by metasoul111** [comment]
we are getting this same issue, it's a show stopper, our end users cannot log in. 
<img width="1205" alt="Screenshot 2023-01-06 at 11 40 55 PM" src="https://user-images.githubusercontent.com/89988259/211057761-ff4fb558-723b-4f2d-880d-5c4f72f566cf.png">

**Comment by designbyfaizi** [comment]
> we are getting this same issue, it's a show stopper, our end users cannot log in. <img alt="Screenshot 2023-01-06 at 11 40 55 PM" width="1205" src="https://user-images.githubusercontent.com/89988259/211057761-ff4fb558-723b-4f2d-880d-5c4f72f566cf.png">

Found a possible fix yet?

**Comment by yashovardhan** [comment]
Hey all,

For this issue the web3auth network you might be working on must be busy at that moment. If you're using `mainnet` I would recommend migrating to `cyan` mainnet which has much more capacity.

**Comment by yashovardhan** [comment]
Please open up a github discussion in the future for us to help you out better in this regard.
