### ISSUE TITLE
Yahoo.com, Hotmail and Other Domains Not Getting Verification Email

### ISSUE THREAD

**Issue by metasoul111** [Web3Auth/web3auth-web#1204]
### Discussed in https://github.com/orgs/Web3Auth/discussions/1156

<div type='discussions-op-text'>

<sup>Originally posted by **metasoul111** January  3, 2023</sup>
Our end users with Yahoo.com, Hotmail, Outlook and some others like t-online.de addresses are not getting the verification email to login. Richard from your support said yesterday that this was fixed but we are still having issues. Can anyone assist?</div>

**Comment by metasoul111** [comment]
This is now an issue with aol.com email addresses as well. Yahoo.com seems to be ok now.

**Comment by chaitanyapotti** [comment]
This is fixed now. We're using two providers. (AWS SES and Sendgrid)
