### ISSUE TITLE
JWT fields during external wallet login have nonstandard names

### ISSUE THREAD

**Issue by ennsharma** [Web3Auth/web3auth-web#1205]
### **Describe the bug**

Web3Auth external wallet login does not sign payloads in a way that's compliant with the [JWT RFC](https://www.rfc-editor.org/rfc/rfc7519). This is problematic because JWT validation from several JWT libraries expects claims that follow the RFC.

### **To Reproduce**

Get a JWT from the [web3auth demo](https://demo-app.web3auth.io/) via external wallet. You can:

- log in with Metamask
- click "Get Auth Id Token"

Try validating the token with [PyJWT](https://pyjwt.readthedocs.io/en/stable/) with a specific expected audience:

```
token = "<your id token>"

jwk_client = jwt.PyJWKClient("https://authjs.web3auth.io/jwks")
key = jwk_client.get_signing_key_from_jwt(token).key

jwt.decode(token, key, algorithms=["ES256"]) # works, decodes fine

jwt.decode(token, key, algorithms=["ES256"], audience="demo-app.web3auth.io") # doesn't work, invalid audience
```

### **Expected behavior**

I'd expect the second line to validate without throwing an invalid audience error too. I think the bug is just that the signed payload when signed by an external wallet includes fields named `"audience"` and `"issuer"` rather than `"aud"` and `"iss"`.

### **Additional context**

I'm not sure if this is a design decision or a bug, but I'd like to know more since I would like to validate these fields with standard libraries.

**Comment by himanshuchawla009** [comment]
thanks for reporting this, we are fixing this. Will keep you posted once we release it.

**Comment by himanshuchawla009** [comment]
feel free to reopen if still face any issue with verification.
