### ISSUE TITLE
CYAN Mainnet - Login/Authentication Error

### ISSUE THREAD

**Issue by subhadeep1010** [Web3Auth/web3auth-web#1214]
### **Describe the bug**

Error - OpenLogin - RPC Error: Invalid params
I am getting this error while trying to authenticate using Custom JWT Token through a Aggregate Verifier(Google and Custom JWT) through CYAN Mainnet. Google Authentication is working fine

Both the verifiers are working on Testnet.

### **To Reproduce**

Integration Code:
`
const web3auth = new Web3AuthCore({
          clientId: 'BAuVJo9zEgWcPSNgchxe9lrhdOvwoMUaKgEKQjn3qgy4SHG1isAD8uBKFmoydIYRBGcWdwuL-aqZdFDMD8bn3lJcs',
          chainConfig: {
            chainNamespace: CHAIN_NAMESPACES.EIP155,
            chainId: "0x5",
            // rpcTarget: "https://eth-goerli.g.alchemy.com/v2/u5IbM_L7RjHwRR_DZG5ysiH3G8iF4-pER", // This is the public RPC we have added, please pass on your own endpoint while creating an app
            rpcTarget: "https://mainnet.infura.io/v3/4393e06727a64e2ebc1ae3a64cfb8a7a", // This is the public RPC we have added, please pass on your own endpoint while creating an app
            // rpcTarget: "https://rpc.ankr.com/eth",
          },
          web3AuthNetwork: "cyan"
        });

        setWeb3auth(web3auth);

        // const openloginAdapter = new OpenloginAdapter();
        const openloginAdapter = new OpenloginAdapter({ adapterSettings: {
          network: "cyan",
          clientId: 'BAuVJo9zEgWcPSNgchxe9lDgOvdhjsoMUaKgEKQjn3qgy4SHG1isAD8uBKFmoydIYRBGcWIsL-aqZdFDMD8bn3lJcs',
          uxMode: "redirect", // other option: popup
          loginConfig: {
            google: {
              verifier: "self-aggregate-verifier", // Pass the Verifier name here. eg. w3a-aggregate-verifier
              verifierSubIdentifier: "self-google-verifier", // Pass the Sub-Verifier here. eg w3a-google
              typeOfLogin: "google", // Pass the type of login provider.
              clientId: "40386855906-u7chrqtvh97cojsusg0ejk1gi6je0vsg3o.apps.googleusercontent.com", // Pass the Google `Client ID` here.
            },
            jwt: {
              name: "terra auth verifier",
              // verifier: "self-jwt-test",
              verifier: "self-jwt-test1",
              // verifier: "self-aggregate-verifier", // Pass the Verifier name here. eg. w3a-aggregate-verifier
              // verifierSubIdentifier: "self-jwt-verifier", // Pass the Sub-Verifier here. eg w3a-google
              typeOfLogin: "jwt",
              clientId: "40386855906-u7chrqtvh97cogshg0ejk1gi6je0vsg3o",
            },
          },
        }});
        web3auth.configureAdapter(openloginAdapter);

        await web3auth.init();
        if (web3auth.provider) {
          setProvider(web3auth.provider);
        }
`

`
const loginJWT = async () => {
    if (!web3auth) {
      uiConsole("web3auth not initialized yet");
      return;
    }
    const web3authProvider = await web3auth.connectTo(
      WALLET_ADAPTERS.OPENLOGIN,
      {
        loginProvider: "jwt",
        extraLoginOptions: {
          id_token,
          verifierIdField: "email", // sub, email, or custom
        },
      }
    );
    setProvider(web3authProvider);
  };
`

### **Expected behavior**

JWT Authentication should work as expected.

### **Screenshots**

![image](https://user-images.githubusercontent.com/19474098/212855426-b1ff88a6-818a-452d-8710-aef3048550cc.png)

**Comment by himanshuchawla009** [comment]
cc: @yashovardhan

**Comment by chaitanyapotti** [comment]
Pls upgrade to the latest version
