### ISSUE TITLE
We are getting various error when we do email verification.

### ISSUE THREAD

**Issue by antmanstar** [Web3Auth/web3auth-web#1217]
Hello nice to meet you and thanks for your kind support every time.
We are using latest version of ```openlogin 2.10.0``` in our front end for web3 authentication.

But from 2 hours ago, we are getting various of issues from torus side.
I am going to attach what exactly we are getting now.

![Image Pasted at 2023-1-17 23-29](https://user-images.githubusercontent.com/43899645/212944287-8523e119-b491-45d6-b1d3-89378931212a.png)

![Screenshot_comcast](https://user-images.githubusercontent.com/43899645/212944431-b45ac208-fc41-4f55-a74a-6bda5fb32048.png)

Some of clients are also getting these issues and blaming us.
Can you please take a look into this problem and hope your kind and powerful help!!!
Thanks all the time.

**Comment by chaitanyapotti** [comment]
All these issues are fixed now. Pls hard refresh the browser
