### ISSUE TITLE
Please pass loginProvider in params while using sessionless redirect mode

### ISSUE THREAD

**Issue by fimak** [Web3Auth/web3auth-web#1262]
### **Please pass loginProvider in params while using sessionless_redirect mode**

Since yesterday we started to get this error: `Please pass loginProvider in params while using sessionless_redirect mode`.
Sometime we get it sometime not.

In your documentation loginProvider is not required. So I don't want to pass it to have all providers.
This is floating bug. Because it is working for some of our users. What to do with it?
We are using react-native-sdk.

### **To Reproduce**

1. Just do the web3.login without providers.
2. See error

### **Expected behavior**

We would like to see web3 popup with all providers. Actually sometime we see it. Sometime we have the error.

### **Screenshots**

<img width="230" alt="image" src="https://user-images.githubusercontent.com/1921713/215816415-bc392b9b-6eb8-4af2-86e2-b72bfb718633.png">

### **Device Info (please complete the following information):**

- Device: [iPhone11], [Realme 9 Pro]
- OS: [iOS], [Android 13]
- Browser: [chrome, safari]
- Version: [109]
- Web3Auth Version [2.1.3]
- Web3Auth React-Native-SDK [3.3.0]

**Comment by chaitanyapotti** [comment]
We have made loginProvider mandatory. 
Reason: App store rejects some apps for displaying login modal inside the custom tabs view. The mandate is that dapps must implement and show all login buttons within their app.
