### ISSUE TITLE
Email Login Not Working On Mainnet

### ISSUE THREAD

**Issue by metasoul111** [Web3Auth/web3auth-web#1280]
### Discussed in https://github.com/orgs/Web3Auth/discussions/1279

<div type='discussions-op-text'>

<sup>Originally posted by **metasoul111** February  3, 2023</sup>
Once you receive the email verification email and click on the button this is the error you get.
This is happening to all our end users and also on web3auth.io

No mail generated. Please initiate the passwordless flow first.

This is happening even when trying to log in to https://dashboard.web3auth.io/

![Screenshot from 2023-02-03 17-01-36](https://user-images.githubusercontent.com/89988259/216727091-b098b252-1d04-43fc-8397-2f598598a565.png)
</div>

**Comment by chaitanyapotti** [comment]
Pls hard refresh the page to fix the issue

**Comment by cocadev** [comment]
No mail generated. Please initiate the passwordless flow first.
Why this is still not working?
