### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ryanberckmans** [Web3Auth/web3auth-web#1287]
Add a license to web3auth-web and also to other dependencies owned by your company, including OpenLoginSdk.

As well, on a somewhat related note, I'll gently suggest that the issue hygiene in this repository has discouraged me from using web3auth. There are many bug reports and issues that have gone unanswered for weeks/months, and that makes me question whether I could rely on the maintainers for support should the need arise.

**Comment by chaitanyapotti** [comment]
Thanks for commenting.. we do periodically review these issues

**Comment by chaitanyapotti** [comment]
License is added
