### ISSUE TITLE
Save recovery phrase email not working

### ISSUE THREAD

**Issue by PJijin** [Web3Auth/web3auth-web#1297]
### **Describe the bug**

I entered my email address on the "Save Recovery Phrase" page, but when I clicked "Continue," no email was sent.

### **To Reproduce**

1. Sign in on web3auth with google.
2. On secure account modal, click on set up 2fa.
3. Click on continue.
4. Enter email address and click continue.

### **Screenshots**
<img width="1196" alt="Screenshot 2023-02-08 at 3 14 51 PM" src="https://user-images.githubusercontent.com/15993065/217499801-ce361c28-6d4c-484d-8281-aa0cfa8d79e0.png">

**Comment by metasoul111** [comment]
We had this issue as well, several of our end users ended up dealing with this and we never got a solution.

**Comment by chaitanyapotti** [comment]
This issue is fixed in v7. Pls upgrade.
