### ISSUE TITLE
NetworkSwitch

### ISSUE THREAD

**Issue by bolisteward** [Web3Auth/web3auth-web#1299]
### **Describe the bug**
Hello, 

I have problems with one of the libraries, it sends me the following error. I tried to import the types, but they already come when installing the UI packages, do you know how to solve this?

### **To Reproduce**
The part below I present a sample of the code where this package is used. This is found in the init function of the service/web3auth module.

`import { NetworkSwitch } from "@web3auth/ui";

const networkUi = new NetworkSwitch()

        const wcAdapter = new WalletConnectV1Adapter({
          adapterSettings: { qrcodeModal: QRCodeModal, networkSwitchModal: networkUi },
          chainConfig: currentChainConfig,
          sessionTime: 86400,
        })

`

Could not find a declaration file for module '@web3auth/ui'. 'e:/Jupyter_Notebook/Proyecto_NFT/React_apps/Landing_app/mint_card/node_modules/@web3auth/ui/dist/ui.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/web3auth__ui` if it exists or add a new declaration (.d.ts) file containing `declare module '@web3auth/ui';`

**Comment by TyrantKingBen** [comment]
Having the same issue with 4.4.0. No issues with 4.3.2, so you could pin the version at 4.3.2 for now (`npm install @web3auth/ui@4.32`, `yarn add @web3auth/ui@4.32`, etc.).

**Comment by TyrantKingBen** [comment]
> Having the same issue with 4.4.0. No issues with 4.3.2, so you could pin the version at 4.3.2 for now (`npm install @web3auth/ui@4.32`, `yarn add @web3auth/ui@4.32`, etc.).

New versions work fine. Not sure what was the issue with 4.4.0 but appears to be fixed.

**Comment by chaitanyapotti** [comment]
This is resolved. Was a bug with a specific version
