### ISSUE TITLE
dot.oracle bridge not able to claim token casper network

### ISSUE THREAD

**Issue by oranje147** [Web3Auth/web3auth-web#1315]
I was using Web3Auth or Torus wallet on the casper network to bridge tokens from BSC network to Casper network using the [dot.oracle](https://bridge.dotoracle.network/) bridge. 

I am however not able to claim the tokens, I do not get a pop-up to sign any transactions whatsoever. Now my funds are stuck in limbo,.

### **To Reproduce**

Use the wallet address of torus when bridging on bridge.dotoracle.network from a metamask wallet address to the casper network. You are than unable to claim and the transaction on the explorer shows: awaiting claim. 

### **Expected behavior**

I expect some popup to sign transaction on the torus wallet. 

### **Screenshots**

Screenshots of console logs are welcome

### **Device Info (please complete the following information):**

- Device: PC
- OS: Windows 11
- Browser: Chrome and Edge
- Web3Auth Version [e.g. 1.0.0]

**Comment by chaitanyapotti** [comment]
Not related to this repo
