### ISSUE TITLE
How to enable ONLY Google and Email Passwordless

### ISSUE THREAD

**Issue by samsoft00** [Web3Auth/web3auth-web#1317]
Please is there a way to enable ONLY these login providers on the modal?
- Google
- Email Passwordless
I have tried multiple approaches but nothing works.
I will appreciate your help.
<img width="759" alt="Screenshot 2023-02-13 at 12 29 05 AM" src="https://user-images.githubusercontent.com/5300891/218343826-f722114f-c13a-419d-a379-86745242f695.png">

**Comment by sistla-gautam** [comment]
Hey,

You can enable which social login to be shown while calling the initModal function. The initModal function takes parameters which decide what type of logins need to be shown. I'm linking the documentation of the same [here](https://web3auth.io/docs/sdk/pnp/web/modal/initialize). Scroll down to the last section (Initializing Modal).

Hope this helps. If this is still unclear, feel free to ask more.
