### ISSUE TITLE
Your Example code of Angular is not working

### ISSUE THREAD

**Issue by Nilbristi** [Web3Auth/web3auth-web#1336]
### Discussed in https://github.com/orgs/Web3Auth/discussions/1334

<div type='discussions-op-text'>

<sup>Originally posted by **arindammojumder** February 16, 2023</sup>
Hello Team,

I have used your **[Using Web3Auth Angular Quick Start Guide](https://web3auth.io/docs/integration-builder?lang=ANGULAR&chain=ETH&evmFramework=WEB3&customAuth=NONE&mfa=DEFAULT&whitelabel=NO&useModal=YES&web3AuthNetwork=TESTNET&rnMode=EXPO&stepIndex=0)** files. But unfortunately it is not working and some variables are also missing, like _isModalLoaded_ on the app.component.ts file.  I think all the files are not updated as per the package.json structure.

While compiling the file I am getting errors regarding some missing files of react. Below I have attached my error log file
[error.txt](https://github.com/Web3Auth/web3auth-web/files/10757733/error.txt)
. Kindly have a look and share your thoughts.

**My system info**

```
Angular CLI: 14.2.10
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.10
@angular/cli                    14.2.10
@schematics/angular             14.2.10
rxjs                            7.5.7
typescript                      4.8.4
```</div>

**Comment by 4strodev** [comment]
Same problem here, currently 2023-08-25 the [angular PnP quickstart guide](https://web3auth.io/docs/quick-start?product=Plug+and+Play&sdk=Plug+and+Play+Web+Modal+SDK&platform=Angular) don't work. There are react missing dependencies. I mean, I would genuinely like to understand why for an angular application you should install react-dom and more dependencies attached to react.

**Comment by chaitanyapotti** [comment]
Hello, the modal sdk uses react internally to render the modal. Most dapps in web3 use react/next.js. so, we mark it as peer dependency. 

you can use the no-modal sdk if installing react dependencies is a concern.
