### ISSUE TITLE
Allow option to force password enter on social login

### ISSUE THREAD

**Issue by vp4655** [Web3Auth/web3auth-web#1355]
### **Is your feature request related to a problem? Please describe.**

Is there a way (I've looked around with no luck), to force password enter for google/facebook/discord on each login attempt? The issue is that we have a use case where multiple people share the same PC and we'd like to prevent one person to login as another becuase everything is remembered.

I mean theoretically they can logout from google and all, but still, it would be ideal if we could force it through web3 modal UI.

### **Describe the solution you'd like**

I'd like to have an option to force people to re-enter password for social login or open modals in icognito window when signing in.

### **Describe alternatives you've considered**

Another option is to allow your modals to be opened in incognito window, ideally as a flag of initModal function or connect function.

**Comment by chaitanyapotti** [comment]
This can be done using the prompt parameter of OAuth2 spec

A typical example would be as follows:

```js
const openloginAdapter = new OpenLoginAdapter({
  loginSettings: {
    extraLoginOptions: { prompt: "login" },
  },
});
```
This prompt parameter needs to be passed in depending on the social login of choice. Pls refer to the corresponding social login documentation.
