### ISSUE TITLE
metamask-adapter not working with brave wallet

### ISSUE THREAD

**Issue by h4gen** [Web3Auth/web3auth-web#1387]
### **Describe the bug**

While connecting with brave the following error is shown on the console:

```
index.js?v=1677568476:99348 error while connecting TypeError: this.provider.once is not a function
    at MetamaskAdapter.connect (index.js?v=1677568476:172935:25)
    at async Web3Auth.connectTo (index.js?v=1677568476:92004:27)
    at async LoginModal.<anonymous> (index.js?v=1677568476:99253:13)
```

the process hangs.

### **To Reproduce**

Try to connect in a browser using brave on [demo page](https://demo-app.web3auth.io/)

### **Expected behavior**

It should connect.

### **Screenshots**

![image](https://user-images.githubusercontent.com/12556763/221935806-6c0ed327-a557-46a4-a4f6-606f6368f4ba.png)

**Comment by chaitanyapotti** [comment]
Thanks for reporting..
Fixed in 5.1.0
