### ISSUE TITLE
Web3Auth returns same JWT token on subsequent logins

### ISSUE THREAD

**Issue by grabbou** [Web3Auth/web3auth-web#1391]
### **Describe the bug**

Logging out and then logging in returns the same JWT token.

### **To Reproduce**

I don't know whether this can be reproduced in your environment, but my steps are simple:
1/ Login
2/ Exp validation fails on the backend
2/ Logout and login again for fresh token
3/ Exp validation fails on the backend

<img width="438" alt="Screenshot 2023-03-05 at 12 59 53" src="https://user-images.githubusercontent.com/2464966/222951351-d73a03c6-b9cf-4a0c-bd15-6e44bf2ecfbc.png">

It is 13:00 right now, and the token expired at 12:09. Maybe the server clock is different and it's not yet expired on your end?

### **Expected behavior**

New token is returned every time I log in

### **Device Info (please complete the following information):**

- Device: iPhone Simulator
- OS: iOS
- Browser: Expo SDK 43
- Web3Auth Version: Latest

I tried removing the app and installing again to ensure no-cache as per the #585 discussion (which had a similar symptoms), but that didn't work.

### **Additional context**

It worked w/o issues yesterday, but only started happening today

**Comment by grabbou** [comment]
Also, is there any way to refresh this token with a refresh token? Didn't find it, that would certainly be super useful in order to re-instantiate a session w/o logging in again.

**Comment by chaitanyapotti** [comment]
We're working on this. Thanks for the report

**Comment by chaitanyapotti** [comment]
This is not an issue anymore with v7. Pls upgrade
