### ISSUE TITLE
Confirmation email comes to Spam folder on Yahoo domain.

### ISSUE THREAD

**Issue by fimak** [Web3Auth/web3auth-web#1394]
### **Confirmation email comes to Spam folder on Yahoo domain.**

Some of our users (not all) are getting the verification code email in the junk folder (Yahoo mail) after rolling out the new version of web3auth.

### **To Reproduce**

1. Try to login with email provider
2. Enter Yahoo email
3. Go to Yahoo inbox there is no mails
4. Open Junk/Spam folder you will see the mail here.

### **Expected behavior**

Mail should get into inbox. Not in Junk/Spam fodler.

**Comment by chaitanyapotti** [comment]
This shouldn't happen unless the user has marked it as spam previously

**Comment by chaitanyapotti** [comment]
This is fixed
