### ISSUE TITLE
Unable to use Web3Auth within Svelte: Cannot demo and display support on Web3-Onboard official docs site

### ISSUE THREAD

**Issue by Adamj1232** [Web3Auth/web3auth-web#1416]
### We are currently unable to support and use the web3Auth package on our official docs site due to build issue within the production env.
There is currently no SvelteKit example and this would be very helpful

Steps to reproduce locally: 

- Clone https://github.com/blocknative/web3-onboard/tree/develop/doc
- Switch branch to `web3Auth_docs_test`
- cd `docs/`
- `yarn`
- `yarn dev` modal displays fine - kill this command
- `yarn build`
- `npm run preview` Modal doesnt load internals

### **Describe the solution you'd like**
The Vite example doesn't work within svelte.config.js

### **Describe alternatives you've considered**

In a production build env the modal pops but is empty.

Docs site repo: https://github.com/blocknative/web3-onboard/tree/develop/docs

web3Auth package: https://github.com/blocknative/web3-onboard/tree/develop/packages/web3auth

### **Additional context**

Try it out here: https://web3-onboard-docs-git-web3authdocstest-blocknative.vercel.app/

<img width="2177" alt="Screen Shot 2023-03-22 at 2 44 07 PM" src="https://user-images.githubusercontent.com/24457880/227033574-be795a9c-a07c-447c-bae6-dee405cb8971.png">

**Comment by tycooperaow** [comment]
@Adamj1232 where you able to find a fix to this issue? I'm still facing it

**Comment by Miami87** [comment]
Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tycooperaow** [comment]
@Miami87 ?

**Comment by Miami87** [comment]
Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yashovardhan** [comment]
Hey folks,

Sorry for the delayed response. This is not the correct channel for asking questions. We are extremely active on https://community.web3auth.io and that is where all the integration questions are answered. 

For this issue particularly, you can have a look at our Svelte troubleshooting guide: https://web3auth.io/docs/troubleshooting/svelte-issues
