### ISSUE TITLE
Not compatible with browsers

### ISSUE THREAD

**Issue by electrovir** [Web3Auth/web3auth-web#1430]
### Describe the bug

web3auth-web is not actually compatible with browsers. Specifically, the `@web3auth/no-modal` package (but I'm sure the same issues apply to the other packages).

- `global`: [randombytes](https://www.npmjs.com/package/randombytes) uses `global`, which does not exist in browsers.
- `process`: [pump](https://www.npmjs.com/package/pump) uses `process`, which does not exist in browsers.
- `Buffer`: [@toruslabs/eccrypto](https://www.npmjs.com/package/@toruslabs/eccrypto) uses `Buffer`, which does not exist in browsers.

There's probably more, but that's where I'm at so far in attempting to use `@web3auth/no-modal`.

### To Reproduce

1. Load the package in any browser

### Workaround

Somewhere in code that gets called before web3auth code gets imported (like in a `<script>` element in `<head>` in `index.html`), create proxies for the incorrect accessors:

```javascript
globalThis.global = globalThis;
globalThis.process = '';
const encoder = new TextEncoder();
globalThis.Buffer = {
    from(input) {
        return encoder.encode(input);
    },
    alloc(size) {
        return new ArrayBuffer(size);
    },
};
```

### Expected behavior

Package works in browsers without error and without workarounds.

### Device Info

- any browser
- any device
- any operating system

**Comment by edmbn** [comment]
I reported the same issue 8 months ago. Referencing #369 here just in case my comment also helps solving this issue.

**Comment by chaitanyapotti** [comment]
I've answered this before but here goes again:
In crypto, we use a lot of elliptic curve packages and most of these are written for node.js and in C++. These libraries are audited by multiple parties and are proven to be reliable.
At Web3Auth, we use these dependencies for crypto operations
The default esm and cjs builds will not be polyfilled for node dependencies and can be polyfilled by the end dapp dev to prevent duplication.

Alternatively, we do provide umd builds with the full polyfills: All packages are available on [jsdelivr](https://cdn.jsdelivr.net/npm/@web3auth/web3auth@0/dist/web3auth.umd.min.js) and [unpkg](https://unpkg.com/@web3auth/web3auth@0/dist/web3auth.umd.min.js) as well

**Comment by chaitanyapotti** [comment]
You can also look at polyfilling for your framework here: https://web3auth.io/docs/troubleshooting/webpack-issues

**Comment by electrovir** [comment]
If this package requires other packages in order to function, this package should _depend_ on those other packages.

Perhaps this package's documentation should be answering this question, if you keep having to answer it yourself. I am not using WebPack, Angular, Vue, or React so the polyfill documentation you linked is not very helpful.

**Comment by electrovir** [comment]
This guide is more closely relevant, though it also contains lots of unnecessary setup and packages installations: https://web3auth.io/docs/troubleshooting/vite-issues. All you need is the few imports and global assignments mentioned in my workaround above.

**Comment by electrovir** [comment]
We eventually gave in and solved our Vite build by adding `vite-plugin-node-polyfills`, dramatically increasing build times and bundle sizes. With dynamic imports it's at least shoved aside into a separate chunk (by far our largest chunk).

However, we use `web-test-runner` for running browser tests, which intentionally has no build process. Thus, for that we simply take care to not write any tests that trigger the dynamic import for this package.

**Comment by paro-paro** [comment]
A full monorepo of "web" packages not compatible with browsers. Crypto at its finest.
