### ISSUE TITLE
Unable to detect login share

### ISSUE THREAD

**Issue by Astrak** [Web3Auth/web3auth-web#1436]
### **Describe the bug**

I've got the "Unable to detect login share" 100% of the time with given clientId+verifier, 0% of the time with another, while both have the exact same configuration on both the dashboard and the client code. The full error message suggests disabling any VPN, but is still there when I do so, and not there with the other setup when I use a VPN, so it's not related to the VPN.

### **To Reproduce**

1. Create a local client
2. Trigger connection
3. See error

### **Expected behavior**

Both accounts with same setup should behave identically

### **Device Info (please complete the following information):**

- Browser [Brave]
- Version [1.49.128]
- Web3Auth Version :
    "@web3auth/base": "^4.6.0",
    "@web3auth/core": "^4.6.0",
    "@web3auth/openlogin-adapter": "^4.6.0",

### **Additional context**

Seems close or identical to https://github.com/Web3Auth/web3auth-web/issues/1238 and https://github.com/Web3Auth/web3auth-web/issues/1375

**Comment by chusla** [comment]
hello i'm seeing this one as well, anyone from web3auth able to provide info on fixes?

![IMG_1660](https://user-images.githubusercontent.com/90009543/228951384-12d14464-a4a2-48d8-8ebf-755e0d2edfcd.jpeg)

**Comment by muhammadqamar** [comment]
facing the same issue, looking for a solution or reply to that

**Comment by mobiman1** [comment]
@chusla @muhammadqamar, are you guys only seeing this issue on first login attempt (after at least 30 minutes or so of no login attempts)? That is what I'm seeing. I think it might be a cold-start latency issue. @Astrak maybe the web3auth app is being hosted on a serverless platform?

**Comment by Astrak** [comment]
It turned out that there was a misspelling error in a verifier field that I overlooked when I checked it. The problem disappeared when I fixed it. 

I was experiencing both error messages actually, "unable to detect login share" as well as "unable to detect device share".

These messages are very misleading.

**Comment by chusla** [comment]
hi all, so far after they said they fixed on their side we ahven't been seeing it as often?  This was received indirectly through a user on a client's page that we helped build with web3auth as wallet connection service

**Comment by yashovardhan** [comment]
This issue has been fixed from our end. Considering there have been major releases in this SDK, we're going ahead to close this issue. Feel free to create a new thread on https://community.web3auth.io if you're still facing any problems.
