### ISSUE TITLE
Phantom logout locked

### ISSUE THREAD

**Issue by lpbonomi** [Web3Auth/web3auth-web#1438]
### **Describe the bug**

After being logged in with Phantom, calling the `logout()` never returns a value

### **To Reproduce**

```
await web3auth.connect() // and connect with Phantom
await logout()
whatever() // This code never gets executed
```
### **Expected behavior**

`logout()` returning a value and continuing code execution

### **Device Info (please complete the following information):**

- Device: [e.g. Macbook pro 2020]
- OS: [e.g. Ventura 13]
- Browser [e.g. chrome]
- Version [e.g. 111]
- Web3Auth Version [e.g. 5.1.0]

**Comment by yashovardhan** [comment]
Hey @lpbonomi can you try this with Web3Auth v6? I was trying to reproduce this issue, but it works fine on our demo applications. Please update this issue accordingly.

**Comment by lpbonomi** [comment]
Hi, II'll try this when issue #1508 is resolved

**Comment by lpbonomi** [comment]
Updated to v7 and it works perfectly, thanks
