### ISSUE TITLE
feature request capacitor plugin

### ISSUE THREAD

**Issue by reslear** [Web3Auth/web3auth-web#1445]
you could conquer the weak market of web3 dApps authenticators since almost no one has developed a plugin for capacitor 

could you consider plans to build a plugin based on your ios/android/web solution into a single plugin?

**Comment by nomadcalendar** [comment]
I agree, having a web3auth plugin for cross-platform apps would be a step forward in onboarding the next million onto Web3. Ionic's Capacitor users or Cordova-based apps alike would benefit from this feature.

**Comment by yashovardhan** [comment]
Can you add this feature request in community.web3auth.io? This repository issues tab is only meant for bugs related to the latest release of our SDK.
