### ISSUE TITLE
Wallet Connect v2

### ISSUE THREAD

**Issue by bolisteward** [Web3Auth/web3auth-web#1446]
### **Describe the bug**

I'm having problems using WalletConnect v2 Adapter with modeless web3auth.
It never connect with walletconnect:
error WalletLoginError: Failed to connect with wallet. Failed to login with wallet connect: Proposal expired

### **To Reproduce**

I am using the same code from the Docs of the page.

import { WalletConnectV2Adapter, getWalletConnectV2Settings } from "@web3auth/wallet-connect-v2-adapter";

const defaultWcSettings = await getWalletConnectV2Settings("eip155", [80001, 137], "myProjectID");
const walletConnectV2Adapter = new WalletConnectV2Adapter({
  adapterSettings: { ...defaultWcSettings.adapterSettings },
  loginSettings: { ...defaultWcSettings.loginSettings },
});

web3auth.configureAdapter(walletConnectV2Adapter);

In connectTo function i have:
const localProvider = await web3Auth.connectTo(WALLET_ADAPTERS.WALLET_CONNECT_V2);

### **Device Info (please complete the following information):**

- Web3Auth Version [5.1.0]
  "@web3auth/base": "^5.1.0",
  "@web3auth/metamask-adapter": "^5.1.0",
  "@web3auth/no-modal": "^5.1.0",
  "@web3auth/openlogin-adapter": "^5.1.1",
  "@web3auth/wallet-connect-v2-adapter": "^5.1.1",

**Comment by chaitanyapotti** [comment]
Pls upgrade to v6. This is solved there
