### ISSUE TITLE
Add and switch chain in Single Factor Auth

### ISSUE THREAD

**Issue by sorus-morenft** [Web3Auth/web3auth-web#1448]
### **Describe the bug**

The `addChain` and `switchChain` methods are absent in the `Web3Auth` object and its interface `IWeb3Auth` for the `@web3auth/single-factor-auth` package, despite the documentation refers to them for implementing chain changes without recreating the object.

### **To Reproduce**

n/a

### **Expected behavior**

Expect to have a common interface among all different `Web3Auth` classes.

### **Screenshots**

n/a

### **Device Info (please complete the following information):**

n/a

### **Additional context**

n/a

**Comment by chaitanyapotti** [comment]
This is released in v6 of single factor auth sdk
