### ISSUE TITLE
Error when using email subaddressing for one of my apps

### ISSUE THREAD

**Issue by FahdW** [Web3Auth/web3auth-web#1455]
### **To Reproduce**

1. Logging in using email subaddressing suddenly breaks one of my apps

### **Expected behavior**

able to login without issue

I have an app that used to work but recently when trying to login i get an error 

`person@email.com` works
`person+1@email.com` doesn not work

```
{}
{"type":"client_report"}
{"timestamp":1682725729.36,"discarded_events":[{"reason":"network_error","category":"session","quantity":1},{"reason":"sample_rate","category":"transaction","quantity":1}]}
```

I get this response back and since it is swallowing the error it is impossible to know what exactly is happening

**Comment by yashovardhan** [comment]
You mentioned this happens with one of your apps. We're able to login correctly in our demo application with Web3Auth v6. Can you please upgrade to the latest SDK and try if this still exists?
