### ISSUE TITLE
Web3Auth no modal SDK is not working with Metamask Adapter on mobile browsers

### ISSUE THREAD

**Issue by mar-s-dev** [Web3Auth/web3auth-web#1459]
### **Describe the bug**
I can't login using Metamask on mobile devices with the no-modal SDK

### **To Reproduce**

1. Clone the demo https://github.com/Web3Auth/web3auth-web/tree/master/demo/react-app-no-modal
2. Replace the default OpenLogin and WalletConnectV1 adapter with Metamask adapter
   ```
    ....
        const init = async () => {
      try {
        const web3auth = new Web3AuthNoModal({
          clientId,
          chainConfig: {
            chainNamespace: CHAIN_NAMESPACES.EIP155,
          },
          web3AuthNetwork: "testnet",
        });

        setWeb3auth(web3auth);

        web3auth.configureAdapter(
          new MetamaskAdapter({
            web3AuthNetwork: "testnet",
            chainConfig: {
              chainNamespace: CHAIN_NAMESPACES.EIP155,
              chainId: "0x1",
              rpcTarget: "https://rpc.ankr.com/eth", // This is the public RPC we have added, please pass on your own endpoint while creating an app
            },
          })
        );
      ....

     const login = async () => {
        try {
          if (!web3auth) {
            uiConsole("web3auth not initialized yet");
            return;
          }
          const web3authProvider = await web3auth.connectTo(WALLET_ADAPTERS.METAMASK);
        .....



   ```
3. Run the project locally and access it on mobile device using router provided IP e.g 192.168.0.3:3000

### **Expected behavior**

Able to login with metamask (similar to modal sdk behavior) 

### **Screenshots**

![IMG_BC56D72B6FAA-1](https://user-images.githubusercontent.com/129494395/236383717-764ae1f1-d148-4840-b74f-4155e1026488.jpeg)

### **Device Info (please complete the following information):**

- Device: [e.g. iPhoneSE2]
- OS: [iOS 15]
- Browser [safari, brave]
### **Additional context**

It works in the desktop browser (chrome)

**Comment by bwasia** [comment]
Hi, any updates on this issue? Did you manage to resolve it?

**Comment by mar-s-dev** [comment]
> Hi, any updates on this issue? Did you manage to resolve it?

Unfortunately no, we had to disable metamask login on mobile devices

**Comment by chaitanyapotti** [comment]
We're working on this. Thanks for the report

**Comment by chaitanyapotti** [comment]
Hello. Metamask adapter only works when metamask extension is present.
As such, you must open it in metamask browser. 
If you want to connect to metamask extension via browser, you need to use wallet-connect-v2-adapter instead
