### ISSUE TITLE
There seems to be some bug in the code. please contact support to fix this.Missing state params #145

### ISSUE THREAD

**Issue by divyesh-frodobots** [Web3Auth/web3auth-web#1464]
### **Describe the bug**

We get this error on one of the user, any idea why that user got this error, for another user it's working fine

Error There seems to be some bug in the code. please contact support to fix this.Missing state params 

![image (1)](https://user-images.githubusercontent.com/125444846/236738666-7b4664fc-ea1b-48cc-b460-143cbdf6de8c.png)

**Comment by chaitanyapotti** [comment]
Pls check the brave shields level
