### ISSUE TITLE
Firebase-next-example error 'dont include validation value web3auth-firebase'

### ISSUE THREAD

**Issue by matbee-eth** [Web3Auth/web3auth-web#147]
```
Error: Could not get result from torus nodes 
 Error occurred while verifying paramsaud validation failed, token values [hideouts-340218] dont include validation value web3auth-firebase
```
Getting this error. I customized some fields to fix it, still no bueno.

**Comment by himanshuchawla009** [comment]
> ```
> Error: Could not get result from torus nodes 
>  Error occurred while verifying paramsaud validation failed, token values [hideouts-340218] dont include validation value web3auth-firebase
> ```
> 
> Getting this error. I customized some fields to fix it, still no bueno.

plz share a sample jwt token and also your verifier name.

**Comment by shahbaz17** [comment]
Hey @matbee-eth 

Please let us know if you've resolved the issue. If not, feel free to continue the conversation on our [community forum](https://web3auth.io/community/). We're closing this issue for now.
