### ISSUE TITLE
Issues with network switch

### ISSUE THREAD

**Issue by xpluscal** [Web3Auth/web3auth-web#1477]
### **Describe the bug**

The documentation states that before switching a chain, you need to add a chain.
The issue is e.g. Goerli network is already present in MM, but web3auth still prompts the user to add a new copy of "Goerli" to networks. This is both annoying and impractical. What is the expected solve here?

Is there also a way to just request a network switch and then update the providers in the app accordingly?
From the modal documentation I see no documentation on network change events or similar.

Please advise on correct approach

### **To Reproduce**

1. Add "addChain" call with standard MM goerli config
2. Call connect

### **Expected behavior**

Existing networks should not need to be re-added as custom networks to Metamask and other wallets.

**Comment by xpluscal** [comment]
I also followed this guide, but method "eth_private_key" is not available for MetaMask:
https://web3auth.io/docs/connect-blockchain/multi-chain#for-ethereum-and-other-evm-compatible-chains

**Comment by chaitanyapotti** [comment]
`eth_private_key` is only supported by openlogin adapters. Other adapters don't reveal the private key.
Regarding addChain, metamask doesn't provide a way to let us know if a chainConfig is already supported. So, we always have to add first and then switch. This is a limitation of metamask

**Comment by xpluscal** [comment]
@chaitanyapotti thank you for your feedback. This is actually not correct, you can check if a chain already exists like this:

```javascript
try {
	await ethereum.request({
		method: 'wallet_switchEthereumChain',
		params: [{ chainId }]
	});

} catch (switchError) {
	console.log(switchError);
	if (switchError.code === 4902) {
		try {
			await ethereum.request({
				method: 'wallet_addEthereumChain',
				params: [
					{
						chainId,
						chainName: _networkName,
						rpcUrls: [_rpcUrl]
					}
				]
			});
		} catch (addError) {
			throw new Error(`Cannot add ${_networkName} with chainId:${_chainId} to your wallet.`);
		}
	} else {
		throw new Error(`Cannot switch to network with chainId:${_chainId} to your wallet.`);
	}
}```
