### ISSUE TITLE
Get link for selected social login

### ISSUE THREAD

**Issue by AndonMitev** [Web3Auth/web3auth-web#1483]
Hello I'm building desktop app with Tauri ( not sure if that matters ) . And when user click on login he is able to see the modal:

<img width="416" alt="image" src="https://github.com/Web3Auth/web3auth-web/assets/32274987/57eae34f-b3ee-4601-9c75-316b63e482d4">

Now after he clicks on Continue withGoogle -> it stucks like this 

<img width="429" alt="image" src="https://github.com/Web3Auth/web3auth-web/assets/32274987/4eff69b7-b3b5-4efd-bafe-48c38bfc8729">

And nothing happens, I have tested exactly the same codebase in browser env and it works.

If you have any suggestions please share but my main question si can i get somehow the link that is coming form oAuth and is poping up the google login modal?

**Comment by chaitanyapotti** [comment]
It might be possible that the popup window is being blocked.
You can use `uxMode: "redirect"` and prefer using that instead
