### ISSUE TITLE
OKTA Integration Guide - Is this coming?

### ISSUE THREAD

**Issue by xpluscal** [Web3Auth/web3auth-web#1505]
### **Is your feature request related to a problem? Please describe.**

The integration guide for OKTA still says "Coming Soon".
It's been like this for at least 3 months - is that still planned?

### **Describe the solution you'd like**

A documentation on it.

Thank you!

**Comment by yashovardhan** [comment]
Can you please ask such questions on https://community.web3auth.io? The issues tab in this repo is meant for bugs. All integration help is present in out Community Portal.
