### ISSUE TITLE
Email code modal is not being displayed on Safari/IOS

### ISSUE THREAD

**Issue by eduzano** [Web3Auth/web3auth-web#1526]
### **Describe the bug**

We noticed that when the user choose to log in using email, the popup is blocked and the email is not being sent. This is not happening on older versions of the sdk.
This happens only in IOS and Safari

### **To Reproduce**

1. Log in using email

### **Expected behavior**

The popup showing the code that has being sent to the user is displayed.

### **Device Info (please complete the following information):**

- Device:
 mobile, computer
- OS: 
 MAC, IOS
- Browser 
 Safari
- Web3Auth Version
 @web3auth/base": "^6.1.1
  @web3auth/modal": "^6.1.1

**Comment by yashovardhan** [comment]
We are able to reproduce this issue, thanks for reporting. We'll be looking into a potential fix for this.

**Comment by IDChats** [comment]
My android mobile device browser is also unable to redirect, but visit https://demo-mpc.web3auth.io/ ,it works

**Comment by alexgerasimov73** [comment]
Any updates?

**Comment by chaitanyapotti** [comment]
This is fixed in 7.3.0 and we throw an error if popup is blocked.
