### ISSUE TITLE
web3 provider not working with v4 

### ISSUE THREAD

**Issue by melsayedgit** [Web3Auth/web3auth-web#1532]
when using social login the provider is not compatible  with newer version of web3, it give this error
![image](https://github.com/Web3Auth/web3auth-web/assets/75117329/6d8fbb2e-5bba-4695-a3e5-994b67eb677e)

**Comment by abdellatif-temsamani** [comment]
same problem

**Comment by melsayedgit** [comment]
> same problem

just use an older version of web3 until they fix it

**Comment by bolisteward** [comment]
is it because of the web3 version and not the web3auth version?

Because the provider when web3auth is started, it sends me a proxy and not a provider object.

**Comment by abdellatif-temsamani** [comment]
> is it because of the web3 version and not the web3auth version?
> 
> Because the provider when web3auth is started, it sends me a proxy and not a provider object.

yes it is because web3 version, Web3auth uses deprecated implementation of web3 provider that is not compatible with web3 4.0.3

**Comment by chaitanyapotti** [comment]
Fixed inn #1590
