### ISSUE TITLE
Scanning the WalletConnect QR code for login does nothing

### ISSUE THREAD

**Issue by ihsraham** [Web3Auth/web3auth-web#1533]
### **Describe the bug**
Logging in via MetaMask mobile app using the WalletConnect QR code gives no response. Noticed this in the example app.

### **To Reproduce**
Scan the WalletConnect QR code in the example app [here](https://github.com/Web3Auth/web3auth-pnp-examples/tree/main/web-no-modal-sdk/evm/react-evm-no-modal-example)

Steps to reproduce the behaviour:

### **Expected behavior**

I was expected to log into the app.

### **Screenshots**

After 5 mins we get a proposal expired error
![image](https://github.com/Web3Auth/web3auth-web/assets/22676435/f013f9ec-f637-44da-9909-46b821098d85)

### **Device Info (please complete the following information):**

- Device: computer
- OS: Mac, Linux(Ubuntu)
- Browser Brave, Chrome
- Web3Auth Version 6.1.1

**Comment by chaitanyapotti** [comment]
Fixed in 6.1.7
