### ISSUE TITLE
latest version failing due to ethereum-cryptography broken version via ethereumjs

### ISSUE THREAD

**Issue by murphman300** [Web3Auth/web3auth-web#1540]
please make sure to version bump up ethereumjs once the PR bellow is merged in

your latest versions are broken otherwise!

**Comment by murphman300** [comment]
https://github.com/ethereumjs/ethereumjs-monorepo/issues/2877

**Comment by chaitanyapotti** [comment]
Thanks. We'll do it

**Comment by murphman300** [comment]
@chaitanyapotti ty!

**Comment by chaitanyapotti** [comment]
Fixed in 6.1.7
