### ISSUE TITLE
when logged in with external wallet, refresh page and switch chain mutilple times, web3auth will disconnect

### ISSUE THREAD

**Issue by raintreasure** [Web3Auth/web3auth-web#1543]
### **Describe the bug**
After logged in using external wallet (metamask), refresh the page, and then switchChain multiple times ( for example, switch between 0x1 and 0x5 back and forth), web3auth will disconnect , ADAPTER_EVENTS.DISCONNECTED event will be triggered, while metamask is still connected. If I execute switchChain again, it will switch success, but metamask modal will not pop out. If I log out, it will report an error :
![image](https://github.com/Web3Auth/web3auth-web/assets/107834302/220480f1-d908-4150-9363-a2666c529e34)
 

### **To Reproduce**

1. Start from web3uath-pnp-examples/web-modal-sdk/evm/react-evm-modal-example, connect with metamask
2. SwitchChain function in react-evm-modal-example switch from 0x1 to 0x5, add a new function to swtich back from 0x5 to 0x1, and listen ADAPTER_EVENTS.DISCONNECTED event
3. refresh page
4. switch back and forth multiple times
5. web3auth will disconnect, ADAPTER_EVENTS.DISCONNECTED event will be triggered, execute switchChain again, it will switch success, but metamask modal will not pop out. If you log out, it will report an error

### **Expected behavior**

web3auth remain connected

- OS: windows wsl
- Browser firefox
- Web3Auth Version "@web3auth/base": "^6.1.1",
    "@web3auth/modal": "^6.1.1",

**Comment by Thebeast44** [comment]
Yes thanks

**Comment by chaitanyapotti** [comment]
This is fixed in v7
