### ISSUE TITLE
web3 1.8.2

### ISSUE THREAD

**Issue by abdellatif-temsamani** [Web3Auth/web3auth-web#1548]
### **Describe the bug**

deprecated version of web3js (1.8.2) the current one 4.0.3

### **To Reproduce**

1. set up a react/nextjs/vue project
2. add web3auth
3. add web3js `the latest version`
4. try the following the get user's address
```typescript 
const web3authProvider = web3auth.provider;

if (web3authProvider) {
    const web3: Web3 = new Web3(web3authProvider);
    const address: string[] = (await web3.eth.getAccounts())[0];
    alert(address);
}
```

5. See error

### **Expected behavior**

get the user's address as `string[]`

### **Device Info (please complete the following information):**

this bug is related the framework/library dependencies.   

- Device: `all`
- OS: `all`
- Browser `all`
- Version `all`
- Web3Auth Version `6.1.3`

### **Additional context**

I would highly recommend migrating to `web3 4.0.3` reffering to web3 docs [***web3.providers Migration Guide | web3.js***](https://docs.web3js.org/guides/web3_upgrade_guide/x/providers_migration_guide)

**Comment by chaitanyapotti** [comment]
v7 works with web3.js 4.x
