### ISSUE TITLE
Trust Wallet failing with Wallet Connect QR Code

### ISSUE THREAD

**Issue by shashank-fox** [Web3Auth/web3auth-web#1560]
### **Describe the bug**

I am trying to scan WalletConnect QR Code on macbook using Trust Wallet App on my phone. It fails with a popup on my mobile phone 
`unsupported or empty accounts for namespace`

 I am trying to connect to Ethereum. Also, please note, the QR Code is working fine with Rainbow. 
 
### **To Reproduce**

In a no-modal integration with Web3auth/nomodal version above 6, try to scan wallet connect qr code using Trust Wallet on phone(  Tested with iphone ). 

### **Expected behavior**

Successful connection with Trust Wallet.

### **Screenshots**

Screenshots of console logs are welcome

### **Device Info (please complete the following information):**

- Device: iPhone 12 and MacBook 
- OS: iOS and MacOS
- Web3Auth Version 6.1.4

**Comment by Thebeast44** [comment]
Oke thanks

**Comment by chaitanyapotti** [comment]
This issue is fixed in the latest version. Pls upgrade
