### ISSUE TITLE
Connected event not fired after redirect succesfull login

### ISSUE THREAD

**Issue by FullStackDevFrancis** [Web3Auth/web3auth-web#1568]
Describe the bug
The connected event is not fired after a successful login redirect using web3auth version 6.1.7 in a Next.js application.

To Reproduce

Click connect here.
https://one-grid-git-development-onegrid.vercel.app/rickyrazu
You will be redirected to the external authentication provider (e.g., MetaMask or another Web3 wallet).
Complete the login process and grant necessary permissions.
After successful authentication, you should be redirected back to the application.
Check console => There are logs in it, some times if you go to main page (https://one-grid-git-development-onegrid.vercel.app) and click connect there it works and you see the connected event fired.

**Comment by yashovardhan** [comment]
Please ask your questions on https://community.web3auth.io alongside your code snippet for us to understand better. It is not possible for us to debug without it. Additionally please have a look at this example in Next.js 

https://github.com/Web3Auth/web3auth-pnp-examples/tree/main/web-modal-sdk/evm/nextjs-evm-modal-example
