### ISSUE TITLE
Switching showOnModal false on eachnof the socials gives error

### ISSUE THREAD

**Issue by ihsraham** [Web3Auth/web3auth-web#1574]
### **To Reproduce**

In the `react-evm-modal` example, when I uncomment the lines 177-203 [here](https://github.com/Web3Auth/web3auth-pnp-examples/blob/main/web-modal-sdk/evm/react-evm-modal-example/src/App.tsx), it gives error on console(see attached screenshot below) when we run the app on local.
```ts
await web3auth.initModal({
  modalConfig: {
    [WALLET_ADAPTERS.OPENLOGIN]: {
      label: "openlogin",
      loginMethods: {
        // Disable facebook and reddit
        facebook: {
          name: "facebook",
          showOnModal: false
        },
        reddit: {
          name: "reddit",
          showOnModal: false
        },
        // Disable email_passwordless and sms_passwordless
        email_passwordless: {
          name: "email_passwordless",
          showOnModal: false
        },
        sms_passwordless: {
          name: "sms_passwordless",
          showOnModal: false
        }
      }
    }
  }
  });
```

### **Expected behavior**
Should load the app without any errors in the console.

### **Screenshots**
<img width="633" alt="Screen Shot 2023-08-08 at 16 25 49 PM" src="https://github.com/Web3Auth/web3auth-web/assets/22676435/6697936a-46ab-4c6c-abf7-45765efdeb3d">

### **Device Info (please complete the following information):**

- Device: MacBook Pro
- OS: Mac OS
- Browser Brave
- Version [Version 1.56.14 Chromium: 115.0.5790.114]
- Web3Auth Version 6.1.7

**Comment by Thebeast44** [comment]
Why?

**Comment by shahbaz17** [comment]
Hey @ihsraham 

Please check once again after updating the package to the latest SDK.
