### ISSUE TITLE
Twitter login not working

### ISSUE THREAD

**Issue by HassanKhan123** [Web3Auth/web3auth-web#1586]
I am integrating auth0 for Twitter login and I have provided all the details following the doc but still getting the error.
Attached is the code for the Twitter login.
![image](https://github.com/Web3Auth/web3auth-web/assets/36511405/813438c7-a7b9-4ee7-bbf9-370bf6f87094)
![image](https://github.com/Web3Auth/web3auth-web/assets/36511405/ce117658-1aeb-4386-a88d-feb9c12a1b20)
![image](https://github.com/Web3Auth/web3auth-web/assets/36511405/56339f87-326d-4286-9604-3ff32e0bbedd)
![image](https://github.com/Web3Auth/web3auth-web/assets/36511405/b292a1dd-c353-402e-8ad5-3544170fc984)
![image](https://github.com/Web3Auth/web3auth-web/assets/36511405/a6b95956-5370-433d-8a7c-70accb2a0704)

verifiedId seems to be undefined here, but I am passing this field.

**Comment by chaitanyapotti** [comment]
verifierIdField value for twitter is `sub` and not `email`.
Email is not always returned in case of twitter login and hence causing your issue.

**Comment by HassanKhan123** [comment]
I am getting this error when I set verifierIdField as sub
![image](https://github.com/Web3Auth/web3auth-web/assets/36511405/f6734562-6606-4c33-bfce-99e3666757b0)
