### ISSUE TITLE
Some time url is Blocking in web3auth and not login

### ISSUE THREAD

**Issue by divyesh-frodobots** [Web3Auth/web3auth-web#1589]
some time login in web3auth show in error and not login in open-login google

Below Show in error list :- 
1) TypeError: Failed to construct 'URL': Invalid URL
2) Error: unknown :-  "OpenLogin - RPC Error: Failed to construct 'URL': Invalid URL"
3) Error: unknown :-  'jrpc response error:'

Below Show in error Image :-
<img width="1458" alt="Screenshot 2023-09-08 at 12 23 38 PM" src="https://github.com/Web3Auth/web3auth-web/assets/125444846/f63010d0-2edd-4957-a643-5735075fcdd5">
<img width="660" alt="Screenshot 2023-09-08 at 12 23 44 PM" src="https://github.com/Web3Auth/web3auth-web/assets/125444846/70ea1f98-2b09-484b-8abd-6842468bc3c8">

**Comment by divbhalala** [comment]
We getting this issue on some users for rest of user it working 
Also for some user, it was not working on the Google Chrome browser it working

**Comment by rakeshlanjewar** [comment]
Upgrading the web3auth dependencies to the latest fixed the issue.

**Comment by divyesh-frodobots** [comment]
> Upgrading the web3auth dependencies to the latest fixed the issue.

@rakeshlanjewar  Can you send me link web3auth upgrade latest npm package.

**Comment by chaitanyapotti** [comment]
Please upgrade to v6 to solve this issue.
It happens because of 3rd party cookies (local storage scoping issue) in modern browsers (chrome 116 too).
v6 already has fixes for this.
