### ISSUE TITLE
web3auth modal email passwordless via cdn suddenly returns error

### ISSUE THREAD

**Issue by kabaluyot** [Web3Auth/web3auth-web#1596]
### **Describe the bug**

web3auth modal (following commonjs web3auth example) suddenly returns error now. It works perfectly in the past days.

### **To Reproduce**

1. Select email passwordless via web3auth modal commonjs (cdn)
2. Enter email and it now returns an error.

### **Expected behavior**

Should be able to login

### **Screenshots**

<img width="1219" alt="Screen Shot 2023-09-14 at 7 19 47 AM" src="https://github.com/Web3Auth/web3auth-web/assets/38805756/cee3b966-4a09-4832-be0a-5f0f9640c090">

### **Device Info (please complete the following information):**

- Device: Macbook
- OS: macOS
- Browser: Safari / Chrome

**Comment by kabaluyot** [comment]
<img width="1219" alt="Screen Shot 2023-09-14 at 7 23 24 AM" src="https://github.com/Web3Auth/web3auth-web/assets/38805756/cba378c6-9474-4a0f-9ee7-d7e529601c95">

For chrome

**Comment by kabaluyot** [comment]
UPDATE: I think the issue is on versioning. Reverted back to 6.1.7 and it works fine now.

<img width="1428" alt="Screen Shot 2023-09-14 at 8 09 30 AM" src="https://github.com/Web3Auth/web3auth-web/assets/38805756/e8d60e35-2727-40e2-9c0b-7401c4f68915">

**Comment by kabaluyot** [comment]
@chaitanyapotti was this addressed with latest version?

**Comment by chaitanyapotti** [comment]
This is fixed now in the latest version
