### ISSUE TITLE
openLogin does not open on Different Chains

### ISSUE THREAD

**Issue by Ronexlemon** [Web3Auth/web3auth-web#1602]
### **Describe the bug**

i have changed the chain to base_Goerli_Testnet it breaks on opening the openlogin for social connect but works on some chains such as polygon

### **To Reproduce**
change all the chains to base_Goerli_Testnet

### **Expected behavior**

No Authentication pop up.
the error :Failed to connect with walletFailed to login with openlogin

### **Screenshots**

Screenshots of console logs are welcome

### **Device Info (please complete the following information):**

- Web3Auth Version [e.g. 1.0.0]

**Comment by chaitanyapotti** [comment]
Pls share the config used

**Comment by chaitanyapotti** [comment]
pls pass correct chain config
