### ISSUE TITLE
 Can't resolve 'object.assign/polyfill' 

### ISSUE THREAD

**Issue by divyesh-frodobots** [Web3Auth/web3auth-web#1603]
when i am updating  6 to 7 i am getting this error , i am using react gatbyjs 
`"@web3auth/base": "^7.0.1",
    "@web3auth/modal": "^7.0.1",
    "@web3auth/solana-wallet-connector-plugin": "^7.0.1",`
    
    
 Can't resolve 'object.assign/polyfill' in 'node_modules/assert/build'
 @ ./node_modules/@web3auth/modal/node_modules/@web3auth/ethereum-provider/dist/ethereumProvider.esm.js 13:0-28 785:4-13 786:4-13 787:4-13 788:4-13 794:10-29 801:8-17 802:8-27
811:12-31 819:10-19 821:10-28 824:12-21 828:12-30 833:8-19
 @ ./node_modules/@web3auth/modal/dist/modal.esm.js 107:14-51
 @ ./src/context/index.js 8:0-43 37:21-29
 @ ./src/pages/spectate.js?export=default 14:0-48 52:38-50
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 14:45-162
 @ ./.cache/app.js 14:0-52 28:87-32:1 31:29-42 34:29-42 28:0-32:2

**Comment by Thebeast44** [comment]
Why?

**Comment by shahbaz17** [comment]
https://github.com/Web3Auth/web3auth-web/issues/1604
