### ISSUE TITLE
Can't resolve object.assign/polyfill

### ISSUE THREAD

**Issue by divyesh-frodobots** [Web3Auth/web3auth-web#1604]
when i am updating 6 to 7 i am getting this error , i am using react gatbyjs
"@web3auth/base": "^7.0.1", "@web3auth/modal": "^7.0.1", "@web3auth/solana-wallet-connector-plugin": "^7.0.1",

Can't resolve 'object.assign/polyfill' in 'node_modules/assert/build'
@ ./node_modules/@web3auth/modal/node_modules/@web3auth/ethereum-provider/dist/ethereumProvider.esm.js 13:0-28 785:4-13 786:4-13 787:4-13 788:4-13 794:10-29 801:8-17 802:8-27
811:12-31 819:10-19 821:10-28 824:12-21 828:12-30 833:8-19
@ ./node_modules/@web3auth/modal/dist/modal.esm.js 107:14-51
@ ./src/context/index.js 8:0-43 37:21-29
@ ./src/pages/spectate.js?export=default 14:0-48 52:38-50
@ ./.cache/this_is_virtual_fs_path/$virtual/async-requires.js 14:45-162
@ ./.cache/app.js 14:0-52 28:87-32:1 31:29-42 34:29-42 28:0-32:2

**Comment by Thebeast44** [comment]
Why?

**Comment by divyesh-frodobots** [comment]
Why? i am getting this error ? any idea ?

**Comment by shahbaz17** [comment]
Hey @divyesh-frodobots 

Ignore the earlier comment, looks like a spammer.

To your question, which polyfill are you using? Also, have you looked at this page? Maybe try the React polyfill at https://web3auth.io/docs/troubleshooting/webpack-issues.

**Comment by ihsraham** [comment]
Hey @divyesh-frodobots,
Please run `npm i -D object.assign` on the terminal and add the following line:
`"object.assign/polyfill": require.resolve("object-assign"),` to the `resolve` block.

Your final `gatsby-node.js` should look like the following:
```
exports.onCreateWebpackConfig = ({ actions, plugins }) => {
    const webpack = require('webpack');
    actions.setWebpackConfig({
        resolve: {
            fallback: {
                crypto: require.resolve("crypto-browserify"),
                stream: require.resolve("stream-browserify"),
                assert: require.resolve("assert"),
                http: require.resolve("stream-http"),
                https: require.resolve("https-browserify"),
                os: require.resolve("os-browserify"),
                url: require.resolve("url"),
                zlib: require.resolve("browserify-zlib"),
                "object.assign/polyfill": require.resolve("object-assign"),
            },
        },
        plugins: [
            plugins.provide({ process: 'process/browser' }),
            new webpack.ProvidePlugin({
                Buffer: ['buffer', 'Buffer'],
            })
        ],
    })
}
```

**Comment by shahbaz17** [comment]
Hey @divyesh-frodobots 

Please use this as your `gatsby-node.js` file:

```js
exports.onCreateWebpackConfig = ({ actions, plugins, getConfig }) => {
    const webpack = require("webpack");
    const path = require("path");
    const config = getConfig();
    if (config.externals && config.externals[0]) {
        config.externals[0]["node:crypto"] = require.resolve("crypto-browserify");
    }
    actions.setWebpackConfig({
        ...config,
        resolve: {
            fallback: {
                crypto: false,
                stream: false,
                assert: require.resolve("assert/"),
                http: false,
                https: false,
                os: false,
                url: false,
                zlib: false,
                "object.assign/polyfill": path.resolve("./node_modules/object.assign/polyfill.js"),
            },
        },
        plugins: [
            plugins.provide({ process: "process/browser" }),
            new webpack.ProvidePlugin({
                Buffer: ["buffer", "Buffer"],
            }),
        ],
    });
};
```

I have a [working example here](https://w3a-gatsby.vercel.app/) using this config: https://github.com/shahbaz17/w3a-gatsby
