### ISSUE TITLE
Login blocked due to unused whitelabel feature

### ISSUE THREAD

**Issue by electrovir** [Web3Auth/web3auth-web#1605]
### **Describe the bug**

On version 7 of `@web3auth/modal` I get errors about plan upgrades for whitelabelling even when I'm not use any whitelabel features at all: my call to `new Web3Auth` has _no_ `uiConfig` property.

### **To Reproduce**

1. Install `@web3auth/modal` v7 via npm
2. Use a base plan clientId
3. Provide _no_ `uiConfig` property to `new Web3Auth()`
4. Try to login (I'm using Google login)
5. See the error (in the screenshot below) 

### **Expected behavior**

I expect to be able to login as on v6, or at least to be able to login with whitelabel configs omitted.

### **Screenshots**

![web3auth](https://github.com/Web3Auth/web3auth-web/assets/1205860/db1db5e8-1b33-42cd-890c-475885c4b66c)

### **Device Info (please complete the following information)😘*

- Device: all of them
- OS: all of them
- Browser: Chrome, Firefox, Safari
- Version: all of them
- Web3Auth Version: 7

**Comment by chaitanyapotti** [comment]
This is fixed now. Thanks for the report
