### ISSUE TITLE
Twitter login issue

### ISSUE THREAD

**Issue by HassanKhan123** [Web3Auth/web3auth-web#1606]
I am integrating auth0 for Twitter login and I have provided all the details following the doc but still getting the error. I am following this link https://web3auth.io/docs/auth-provider-setup/social-providers/twitter#example
Attached is the code for the Twitter login.
![image](https://github.com/Web3Auth/web3auth-web/assets/36511405/32520d6a-504d-425f-ae74-3e6938dbd235)
![image](https://github.com/Web3Auth/web3auth-web/assets/36511405/a0db62eb-38a5-43c2-a4a8-51c764243fb1)
![image](https://github.com/Web3Auth/web3auth-web/assets/36511405/67ff4ba8-b602-4bdf-9e45-19c02ec1c42f)

**Comment by chaitanyapotti** [comment]
Pls ask this question on https://web3auth.io/community/
