### ISSUE TITLE
Modal not rendering text

### ISSUE THREAD

**Issue by lpbonomi** [Web3Auth/web3auth-web#1615]
### **Describe the bug**

<img width="428" alt="Screenshot 2023-10-05 at 16 52 38" src="https://github.com/Web3Auth/web3auth-web/assets/38361000/eaf10103-3e9a-45d9-b5d0-394404efbc0c">

### **To Reproduce**

1. Login
2. Logout
3. Login again

Couldn't isolate the issue in a reproduction repo

### **Device Info (please complete the following information):**

Multiple devices, multiple os
```
"@web3auth/base": "^7.0.1",
"@web3auth/core": "^4.6.0",
"@web3auth/modal": "^7.0.3",
"@web3auth/openlogin-adapter": "^7.0.1",
"@web3auth/phantom-adapter": "^7.0.2",
"@web3auth/solflare-adapter": "^7.0.2",
```

### **Additional context**

In v5 I didn't have this problem

**Comment by chaitanyapotti** [comment]
Should be fixed in v7.0.4
