### ISSUE TITLE
 Failed to connect with wallet. Wallet adapter is not ready yet, Please wait for init function to resolve before calling connect/connectTo function

### ISSUE THREAD

**Issue by vis1onn** [Web3Auth/web3auth-web#1619]
### **Describe the bug**

```
 "@web3auth/base": "^7.0.4",
 "@web3auth/modal": "^7.0.5"
```

I can't re-login using the same adapter.
Youn need to log in and after logging out I can’t log in again, I get an error that the adapter is not ready yet. This applies to any adapters (opelogin, or any other external wallet)

### **To Reproduce**

1. Make a login using any adapter
2. Logout
3. Make a login using the same adapter

### **Expected behavior**

I need to be able to login using the same adapter multiple times.
WITHOUT REINITIALIZING THE WEB3AUTH MODAL WINDOW AND WITHOUT RELOADING THE PAGE

### **Temporary solution**
Reinitialization of the web3auth.modal after each logout.

### **Screenshots**

![image](https://github.com/Web3Auth/web3auth-web/assets/30551708/890a39ee-8b99-46aa-8147-ea841fc4ee68)

### **Device Info:**

- UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 
- Web3Auth Version 7.0.4/7.0.5

### **Additional context**

This problem did not exist on previous versions (6 and below)

```
web3auth = new Web3Auth({
      clientId: import.meta.env.VITE_WEB3AUTH_CLIENT_ID,
      web3AuthNetwork: web3AuthConfig.value.network,
      chainConfig: {
        chainNamespace: CHAIN_NAMESPACES.EIP155,
        chainId: web3Config.value?.network?.chainId,
        rpcTarget: web3Config.value?.network?.provider
      },
      defaultLanguage: "en",
      modalZIndex: "99998",
    });

    const host = import.meta.env.VITE_APP_HOST
    const openloginSettings = {
      loginSettings: {
        mfaLevel: "none"
      },
      adapterSettings: {
        replaceUrlOnRedirect: true,
        redirectUrl: host + '/deals/all'
      }
    };

    if (userDevice.value === 'mobile') {
      openloginSettings.adapterSettings.uxMode = 'redirect';
      openloginSettings.loginSettings.appState = JSON.stringify({
        ...(router.currentRoute.value.query || {}),
        redirectFrom: undefined
      });
    }

    const openloginAdapter = new OpenloginAdapter(openloginSettings);
    web3auth.configureAdapter(openloginAdapter);

    await web3auth.initModal({
      modalConfig: {
        openlogin: {
          showOnModal: window === top // Do not show for iframes
        }
      }
    });

```

**Comment by Thebeast44** [comment]
Thanks please

**Comment by shahbaz17** [comment]
Hey @vis1onn 

Please update the Web3Auth SDK to the latest version and try again.

**Comment by chaitanyapotti** [comment]
we've tested this. Not able to reproduce. Pls update to the latest version and try again
