### ISSUE TITLE
Not sending recovery share mail when defaultLanguage set as Portuguese

### ISSUE THREAD

**Issue by ihsraham** [Web3Auth/web3auth-web#1621]
### **Describe the bug**
I am able to send recovery phrase mail when defaultLanguage is set as English but not when it is set as Portuguese.

### **To Reproduce**

1. In react-evm-no-modal example, set defaultLanguage as "pt" and run it on local.
2. Log in with the email for which MFA has never been set up
3. After entering the recovery email different than the one used to login, it does not send a mail, nothing happens.

### **Expected behavior**

A mail should be sent and it should proceed to showing a box to enter the received recovery share.

### **Screenshots**

<img width="1501" alt="Screenshot 2023-10-20 at 12 56 09 PM" src="https://github.com/Web3Auth/web3auth-web/assets/22676435/960ffb95-6cc5-4604-b1e5-2ac4c3b669d4">

<img width="1312" alt="Screenshot 2023-10-20 at 1 04 34 PM" src="https://github.com/Web3Auth/web3auth-web/assets/22676435/6b390869-c84e-4cce-bb07-402c4873d0dc">

### **Device Info (please complete the following information):**

- Device: MacBook Pro M2 Pro
- OS: MacOS Sonoma
- Browser Brave
- Version: 1.59.117
- Web3Auth Version: 7.0.4

**Comment by Thebeast44** [comment]
Thanks

**Comment by chaitanyapotti** [comment]
This is fixed now
