### ISSUE TITLE
Uncaught (in promise) Error: Method not supported. "solanaPrivateKey"

### ISSUE THREAD

**Issue by lpbonomi** [Web3Auth/web3auth-web#1623]
### **Describe the bug**

Can't get the private key from the user

### **To Reproduce**

1. Click "Connect"
2. Click "Get Private key"

### **Expected behavior**

Get the user's private key

### **Screenshots**

![Screenshot 2023-10-26 at 20 39 40](https://github.com/Web3Auth/web3auth-web/assets/38361000/8b59aa19-8b04-47b8-8c59-cee573763ff3)

### **Device Info (please complete the following information):**

- Device: Macbook 2020 M1
- OS: OSX 14.1
- Browser: Chrome
- Web3Auth Version: 7.0.5

Minimal reproduction repo: https://github.com/lpbonomi/web3auth-repro

**Comment by lpbonomi** [comment]
The web3auth examples doesn't work either:

https://github.com/Web3Auth/web3auth-pnp-examples/tree/main/web-modal-sdk/solana/nextjs-solana-modal-example

**Comment by esqlea** [comment]
We are having the same issue

**Comment by yashovardhan** [comment]
Hey folks,

Please check the latest examples on Solana: https://github.com/Web3Auth/web3auth-pnp-examples/tree/main/web-modal-sdk/blockchain-connection-examples/solana-modal-example

As I see it is working fine.

**Comment by yashovardhan** [comment]
Further, please ask the questions on https://community.web3auth.io

We'll be promptly looking into it.

**Comment by lpbonomi** [comment]
Yes, it looks like it started working again. Could it have been a RPC error?
