### ISSUE TITLE
Modal Widget freezes on mobile

### ISSUE THREAD

**Issue by MakiBM** [Web3Auth/web3auth-web#1632]
### **Modal Widget freezes on mobile**

When trying to log using social methods modal freezes

### **To Reproduce**

1. Go to https://demo-app.web3auth.io/
2. Click on Connect
3. Click on 'Continue with Google'

### **Expected behavior**

Should log in as on the desktop

### **Screenshots**

https://github.com/Web3Auth/web3auth-web/assets/4959890/20161569-5768-4041-ae67-db71d212a547

### **Device Info **

- Device: Iphone 14 pro
- OS: ios 16
- Browser Safari
- Web3Auth Version - current

**Comment by abigail-0111** [comment]
I have the same problem. It seems like pop-ups are disabled in Safari..have any ideas?

**Comment by abigail-0111** [comment]
Find it.. https://web3auth.io/community/t/safari-blocking-popups-is-there-a-redirect-option-for-plug-and-play/5599
Mentioned here "If your user base has a lot of safari users, please use redirect instead of popup."

And i'm using redirect instead of popup in my app, safari works.
