### ISSUE TITLE
Incorrect typed signature in some cases

### ISSUE THREAD

**Issue by evgenynacu** [Web3Auth/web3auth-web#1644]
### **Describe the bug**

eth_signtypeddata_v4 works incorrectly in some cases: it seems hash is calculated incorrectly when message contains empty array.
here is a message which is signed correctly: https://gist.github.com/evgenynacu/0f98676af54224982c19de80d33f9ea2
this is a message which is signed incorrectly: https://gist.github.com/evgenynacu/1b14365c838f03e17fe870095eecbff2

### **To Reproduce**

1. Prepare a EIP-712 message which contains empty bytearray (see example)
2. invoke eth_signtypeddata_v4 with this message
3. get signature
4. check if signature is correct

### **Expected behavior**

Signature should be verified correctly

### **Device Info (please complete the following information):**

- Device: Macbook pro
- OS: MacOS
- Browser: Chrome
- Version: Chrome 119.0
- Web3Auth Version
    "@web3auth/base": "^7.1.0",
    "@web3auth/modal": "^7.1.1",

**Comment by chaitanyapotti** [comment]
Fixed in 7.2.0
