### ISSUE TITLE
The EthereumProvider library seems to have a large bundle size

### ISSUE THREAD

**Issue by masaya48** [Web3Auth/web3auth-web#1653]
### **Is your feature request related to a problem? Please describe.**

The EthereumProvider library seems to have a large bundle size. Tree shaking does not work either.

### **Describe the solution you'd like**

I think there are several solutions

1. EthereumProvider offers multiple Providers, but there are no dependencies between them. However, when they are provided, they are integrated into one bundle file. I think this is a factor that prevents tree shaking. Is it possible to offer them in separate bundle files?
2. Are you using unnecessary libraries? For example, bn.js and bignumber.js are libraries that provide similar functionality, so it may be possible to use one or the other.
3. Can the side effects be nullified? It is not certain how effective it would be, but specifying `sideEffects: false` or giving a pure annotation might encourage tree shaking.

**Comment by masaya48** [comment]
The size of the EthereumProvider bundle size seems to depend on the base-controller.

Is there any way to reduce the bundle size, for example by excluding the base-controller dependencies lodash or using lodash-es?

The base-controller repository does not seem to be publicly available, so I could not see the implementation and could only see that lodash is large.

**Comment by chaitanyapotti** [comment]
Thanks for this issue. we're looking into reducing bundle size with web3auth v8

**Comment by masaya48** [comment]
Thank you! Looking forward to a great v8.
Do you plan to reduce web3auth-mpc-web as well?

**Comment by chaitanyapotti** [comment]
The bundle size was considerably reduced with v8. For mpc as well

**Comment by freeatnet** [comment]
@chaitanyapotti Appreciate your work on this!

I was wondering if there's a chance you guys could clean up/split up `@toruslabs/base-controllers`. It's the last bit of web3auth's code that seems to add a lot of dead code for us.

Specifically, with our next@v14.2.3 app:

* If `@toruslabs/base-controllers` is reduced to `{ BaseController, concatSig, createEventEmitterProxy, createFetchMiddleware, randomId, signChallenge, signMessage, verifySignedChallenge }` (which are all the exports consumed in web3auth-web repo), we get a 37KB reduction in first load JS across every page that loads web3auth — that's 7% less first load JS for our average page.
* Further, if `@toruslabs/base-controllers` is reduced to `{ BaseController, createEventEmitterProxy, createFetchMiddleware }` (with signing methods perhaps split out closer to their consumers) at the base layer, we'd save approximately 50KB — that's a full 10% improvement for us.

I'm happy to set up a sandbox with our bundle size analyzer suite to provide a reproduction — let me know, happy to help here.

**Comment by chaitanyapotti** [comment]
Please setup the sandbox. Since, we consume only those exports, the tree-shaking should've eliminated the remaining code.

**Comment by freeatnet** [comment]
@chaitanyapotti sure, here it is: https://github.com/freeatnet/web3auth-treeshaking-repro

1. `base-controllers` as-is: [585kB first load JS](https://github.com/freeatnet/web3auth-treeshaking-repro/actions/runs/9427954023/job/25972713652#step:6:44)
2. Unused exports removed [via a patch](https://github.com/freeatnet/web3auth-treeshaking-repro/pull/1/files#diff-859c6aafd275e33ba54fdb8c21f3a4bfd8bd0f75f6ed5aa640c40c35066fb4b1): [554kB first load JS](https://github.com/freeatnet/web3auth-treeshaking-repro/actions/runs/9427986286/job/25972787169?pr=1#step:6:44)

**Comment by chaitanyapotti** [comment]
Hello, we've found some reasons and would be releasing a new minor update for web3auth sdk next week. This would enable full real tree-shaking across our entire stack and result in significant bundle size reductions.

Thanks for reporting this.

**Comment by freeatnet** [comment]
@chaitanyapotti can't seem to reach you on any social media, so I'm posting here. We got user feedback saying the "generating your key on" flow feels quicker now. Obviously, that's not a part we manage, so I wanted to forward the feedback. Thank you for your work on performance!

**Comment by chaitanyapotti** [comment]
You should try out our v9 sdk where this is reduced from 960 KB to 350KB now.
v9 is currently under active testing right now. Will be releasing it next week.
