### ISSUE TITLE
[web3auth/modal] No support for idToken refresh?

### ISSUE THREAD

**Issue by paro-paro** [Web3Auth/web3auth-web#1655]
Hello,

Maybe I am wrong... but I was going through the docs and I did not find any information on how to refresh the id token so we can achieve persistent login in web applications. I am using the plug & play `web3auth/modal` package.

I know we can set the `sessionTime` option up to a max value of 7 days but after that the user will be forced to re-authenticate manually. 

Any plans on adding refresh token support so we can leverage this feature? Or maybe I am missing something?

I will really appreciate your answer since our client has asked for persistent login as a requirement and I believe that I cannot achieve this with web3auth. 

Thanks in advanced!

**Comment by chaitanyapotti** [comment]
we currently don't support session refresh and don't plan on adding support for it anytime soon due to security reasons. Long lived sessions are prone to hijacks. 
Alternatively, you can use core-kit to configure session time to your convenience.
