### ISSUE TITLE
Connect function will occasionally not pop open modal

### ISSUE THREAD

**Issue by Ian-Bright** [Web3Auth/web3auth-web#1659]
### **Describe the bug**

When calling the "connect" function on a next.js app there are occasions where the function will never open the modal. When logging you can log above it, but no promise is ever resolved, no error is ever thrown, and the code below "connect" does not execute. 

### **To Reproduce**

1. Connect to web3 modal. Create the client inside of a useEffect in the app file or inside of a context (somewhere high up app tree)
2. Refresh the page one or two times (this does not work every time)
3. Call the logout function
4. Attempt to connect again. If the bug is reproduced then the modal will not open

### **Expected behavior**

There should be some sort of feedback as to what is happening. No error message is thrown, the code doesn't appear to be executing, we seem stuck in a promise with no obvious solution on how to fix this.

### **Screenshots**

<img width="1421" alt="Screenshot 2023-12-11 at 5 58 21 PM" src="https://github.com/Web3Auth/web3auth-web/assets/66142236/940b14f4-1931-4835-a656-3f1fe76ba0f1">

<img width="868" alt="Screenshot 2023-12-11 at 5 58 38 PM" src="https://github.com/Web3Auth/web3auth-web/assets/66142236/1b60de13-0143-400a-91e0-a6c342fc18b6">

### **Device Info (please complete the following information):**

- Device: Macbook Air
- OS: macOS
- Browser Brave
- Version 1.52.129
- Web3Auth Version 7.2.0

**Comment by chaitanyapotti** [comment]
Hello, 7.3.0 throws if the popup is blocked
