### ISSUE TITLE
CommonJS module syntax Error on @web3auth/base openlogin-adapter, ethereum-provider etc

### ISSUE THREAD

**Issue by softwarecurator** [Web3Auth/web3auth-web#1662]
### **Describe the bug**

```bash
|- SyntaxError: [vite] Named export 'EthereumPrivateKeyProvider' not found. The requested module '@web3auth/ethereum-provider' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@web3auth/ethereum-provider';
const {EthereumPrivateKeyProvider} = pkg;
```

### **To Reproduce**

1. npm create svelte@latest my-app
2. install web3auth packages 
3. import packages

### **Expected behavior**

being able to run the app

### **Screenshots**
![Screenshot 2023-12-14 at 1 30 01 PM](https://github.com/Web3Auth/web3auth-web/assets/43492172/78ad7c1e-4e15-4f81-884b-7a32b0c2a9c2)

### **Device Info (please complete the following information):**

- Device: Mac Mni
- OS: Mac OS
- Browser Chrome
- Version 120.0.6099.71
- Web3Auth Version ^7.0.1 (latest)

**Comment by chaitanyapotti** [comment]
If your package uses module syntax, 
you must import web3auth sdks using

```
import pkg from '@web3auth/ethereum-provider';
const {EthereumPrivateKeyProvider} = pkg;
```
