### ISSUE TITLE
While connecting to Tezos, chainID is mandatory on the code but not on the documentation

### ISSUE THREAD

**Issue by zamrokk** [Web3Auth/web3auth-web#1667]
The line responsible of the failure 

` if (!config.chainConfig.chainId) throw WalletInitializationError.invalidProviderConfigError("Please provide chainId inside chainConfig");`
  
  The Tezos documentation
  
  https://web3auth.io/docs/connect-blockchain/tezos#initializing-provider

**Comment by chaitanyapotti** [comment]
chainId is mandatory and docs have been updated accordingly
