### ISSUE TITLE
[PRIVATE KEY] Use PrivateKey as seed

### ISSUE THREAD

**Issue by Amurmurmur** [Web3Auth/web3auth-web#1708]
### **Is your feature request related to a problem? Please describe.**

hey guys, quick question
When I get a PK from a web3auth, is this meant to be used as an entropy for EVM chains.
Or is it a good practice to derive a seed from the web3auth pk and generate wallets on any chain ?

for example:
```
HDKey.fromMasterSeed(web3auth.privKey)
```

**Comment by chaitanyapotti** [comment]
You can do that. Yes.
