### ISSUE TITLE
Including @web3auth/modal dependency causes a polyfill error in Angular 15.5

### ISSUE THREAD

**Issue by mchaver** [Web3Auth/web3auth-web#1720]
When including `@web3auth/modal` in an angular project (currently version 15.5), I get the following error when running `ng server`.

```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "zlib": require.resolve("browserify-zlib") }'
	- install 'browserify-zlib'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "zlib": false }
```

I followed the suggested solution here https://web3auth.io/docs/troubleshooting/webpack-issues#angular
I got the same error and then I did ` npm install browserify-zlib` and updated tsconfig.json to include: `"zlib": ["./node_modules/browserify-zlib"]`. But I am still getting the same result.

**Comment by ihsraham** [comment]
Hey @mchaver,

I've looked into it, and it appears there isn't a version 15.5 of Angular available. Could it be possible you were referring to version 15.1.5? On our end, I've updated our evm-modal-quickstart example to the latest v15 LTS version, which is 15.2.10. The update is on the branch named `test-angular-v15`. You can check out the example using this [link to the branch](https://github.com/Web3Auth/web3auth-pnp-examples/tree/test-angular-v15/web-modal-sdk/quick-starts/angular-modal-quick-start).

Please let me know if this helps or if there's anything else I can do to assist you further.
