### ISSUE TITLE
Whitelabel empty object

### ISSUE THREAD

**Issue by marcollilorenzo** [Web3Auth/web3auth-web#1738]
I create a OpenLoginAdapter instance in this way:

`return new OpenloginAdapter({

    adapterSettings: {
      uxMode: 'redirect',
      whiteLabel: {
        logoDark: 'https://...',
        logoLight: 'https://...',
        appName: 'App name',
        appUrl: 'https://...',
        defaultLanguage: 'en',
        theme: {
          primary: '#000000',
        },
        useLogoLoader: true,
      },

      loginConfig: {

        jwt: {
          verifier: auth0Verifier,
          typeOfLogin: 'jwt',
          clientId: auth0ClientId,
          logoDark: 'https://...,
          logoLight: 'https://...,

        },
      },

    },

    privateKeyProvider: privateKeyProvider as PrivateKeyProvider,
  });`
  
  But when i console log the instance, whiteLabel is empty:
  
  `{
    
    "openloginInstance": {
       
        "options": {
            "network": "sapphire_devnet",
            "clientId": "BKHLX_noLgu67-pALS9SIf_AGOv42YD5wi-vopDxW26VsMgBPryeD8Ha140RYLuyPFp0yuX_qYjJL0pwp6e6pCU",
            "uxMode": "redirect",
            "whiteLabel": {},
            "loginConfig": {
                "jwt": {
                    "verifier": "auth0-project-web3-test",
                    "typeOfLogin": "jwt",
                    "clientId": "LvEaQU0LiOACJD8YokQj63Pod4ymxS0X",
                    "logoDark": "https://dev.finest.investments/logo-dark.png",
                    "logoLight": "https://dev.finest.investments/logo-dark.png"
                }
            },
}`

And i try to use WalletPluginService and i receive this error
`
WalletServicesPlugin: Error: logoDark and logoLight are required in whiteLabel config`

**Comment by chaitanyapotti** [comment]
the whitelabel config you pass in uiConfig of web3auth constructor overrides the ones passed in adapter constructor. hence, you see the empty object. we recommend configuring whitelabel in web3auth constructor
