### ISSUE TITLE
EthereumPrivateKeyProvider does not support the eth_requestAccounts method

### ISSUE THREAD

**Issue by rabbitmouse** [Web3Auth/web3auth-web#1752]
I need to construct a provider that conforms to the EIP-1193 protocol to accept wallet connection requests, but eth_requestAccounts will be called instead of eth_accounts?

Then I found the following description in eip-1193 documentation [https://eips.ethereum.org/EIPS/eip-1193](https://eips.ethereum.org/EIPS/eip-1193)
“Providers should support RPC methods for explicitly requesting account access, such as eth_requestAccounts (see EIP-1102) ”

And meta-mask also supports this method. 
[https://docs.metamask.io/wallet/reference/eth_requestaccounts/](https://docs.metamask.io/wallet/reference/eth_requestaccounts/)

Can you provide support for this method?

**Comment by chaitanyapotti** [comment]
eth_requestAccounts is the same as calling the connect method.
With web3auth sdk, supporting eth_requestAccounts is not straightforward because we wouldn't know which adapter you want to connect to.
