### ISSUE TITLE
idToken missing in getUserInfo() – web3auth 8.3.0

### ISSUE THREAD

**Issue by remibeaufils** [Web3Auth/web3auth-web#1795]
### **Describe the bug**

Suddenly web3auth.getUserInfo() does not contain the idToken anymore.

### **To Reproduce**

Install & Run the official example https://github.com/Web3Auth/web3auth-pnp-examples/tree/main/web-modal-sdk/quick-starts/nextjs-modal-quick-start

Connect then execute web3auth.getUserInfo().

Problem: web3auth.getUserInfo() does not contain idToken.

### **Expected behavior**

web3auth.getUserInfo() should contain the idToken. The token issued by Web3Auth.

### **Device Info (please complete the following information):**

- Device: mac
- OS: iOS 14.4.1 (23E224)
- Browser chrome
- Version 123.0.6312.123 (Official Build) (arm64)
- Web3Auth Version latest (8.3.0)

### **Additional context**

With @web3auth/modal 7.3.0 it works, web3auth.getUserInfo() contains the idToken

**Comment by chaitanyapotti** [comment]
This should be fixed now. No need to make any code changes
