### ISSUE TITLE
Wagmi + TorusWalletAdapter fails to connect - error in no-modal.ts

### ISSUE THREAD

**Issue by W3stside** [Web3Auth/web3auth-web#1913]
### **Describe the bug**

Context: 
1. web3auth `8.12.4`, @web3auth/torus-evm-adapter `8.12.4`, wagmi `2.12.7`, viem `2.20.1`, 
2. `wagmi` app using `Web3AuthConnector`
3. adapters: `OpenLogin` and `TorusWalletAdapter`

When connecting to `web3auth` and selecting `ExternalWallet` --> `TorusWallet` as below:
<img width="496" alt="image" src="https://github.com/user-attachments/assets/0eaf782b-2b32-4b25-a69d-692dba560e3f">

- Torus wallet initiation works fine, I can select my google account etc.
- However, on loading config after approving connection, it fails to connect because:
- On initiation inside of `no-modal.esm.js` inside the `no-modal` subpackage, specifically `subscribeToAdapterEvents` on `L236`, the function calls for the `data` event from `walletAdapter.on(ADAPTER_EVENTS.CONNECTED, async data => {` - `L237` which expects the `provider` prop to be present - it isn't, this causes an error on `L243`: `this.commonJRPCProvider.updateProviderEngineProxy(provider.provider || provider);` as `provider.provider || provider` does not exist
<img width="923" alt="image" src="https://github.com/user-attachments/assets/dbfeb1ef-a891-4138-9416-719dffaedda5">

### **To Reproduce**
Use the versions: web3auth `8.12.4`, @web3auth/torus-evm-adapter `8.12.4`, wagmi `2.12.7`, viem `2.20.1`, 
Start a repo and add `Web3AuthConnector`with `TorusWalletAdapter` with a similar config:
```ts

new TorusWalletAdapter({
    clientId: process.env.REACT_APP_WEB3AUTH_DEVNET_CLIENT_ID,
    adapterSettings: {
      buttonPosition: 'bottom-left'
    },
    loginSettings: {
      verifier: 'google'
    },
    sessionTime: 3600 // 1 hour in seconds
  })
```
- Select ExternalWallets, click Torus, connect gmail account, wait for successful connect and modal close. It should fail!
- Open console and check the error: 
<img width="409" alt="image" src="https://github.com/user-attachments/assets/b84673e9-f2f0-40ff-a7af-06f55f8dd0ad">

### **Expected behavior**

It should close the modal and connect

### **Device Info (please complete the following information):**

- Device: Macbook Pro
- OS: MacOS latest
- Browser Chrome latest
- Web3Auth Version `8.12.4`

### **Additional context**

Fix can be as followed:
[Link to file and place in question for fix](https://github.com/Web3Auth/web3auth-web/blob/d698fbfe7bf871a059d42c33cb89beb18ba3d622/packages/no-modal/src/noModal.ts#L302)
`@web3auth/no-modal` > `no-modal.ts`

```ts
...
subscribeToAdapterEvents(walletAdapter) {
walletAdapter.on(ADAPTER_EVENTS.CONNECTED, async data => {
  if (!this.commonJRPCProvider) throw WalletInitializationError.notFound(`CommonJrpcProvider not found`);
  const {
    adapter,
    provider: _provider
  } = data;
  const provider = this.getAdapter(adapter) || _provider
  this.commonJRPCProvider.updateProviderEngineProxy(provider.provider || provider);
// ... rest of subscribeToAdapterEvents code
```

**Comment by W3stside** [comment]
probably more relevant to fix https://github.com/Web3Auth/web3auth-web/issues/1914

noticed after the fact but linked both. culprit likely the `as` type cast in `TorusWalletAdapter`

**Comment by muratyayla26** [comment]
same error for torus-solana-adapter also as the no-modal.ts is common file. Thanks for the solution @W3stside , I applied that for my local dist files and it works, I hope fix is gonan be merged.

**Comment by chaitanyapotti** [comment]
Fixed in v9
