### ISSUE TITLE
missing provider in connect `emit` throws in `no-modal.ts`

### ISSUE THREAD

**Issue by W3stside** [Web3Auth/web3auth-web#1914]
## Bug - missing provider in connect `emit` throws in `no-modal.ts`

https://github.com/Web3Auth/web3auth-web/blob/d698fbfe7bf871a059d42c33cb89beb18ba3d622/packages/adapters/torus-evm-adapter/src/torusWalletAdapter.ts#L140

connected to issue in https://github.com/Web3Auth/web3auth-web/issues/1913

should additionally `emit` the `provider` like: 

```ts
// L140 --> connect code
// ... rest of connect code
this.emit(ADAPTER_STATUS.CONNECTED, { 
  adapter: WALLET_ADAPTERS.TORUS_EVM, 
  reconnected: this.rehydrated, 
  provider: this.provider // <-- this is the lacking line
} as CONNECTED_EVENT_DATA);
// ... rest of connect code
```

**Comment by W3stside** [comment]
MR: https://github.com/W3stside/wagmi-web3auth-example

**Comment by chaitanyapotti** [comment]
Fixed in v9
