### ISSUE TITLE
Interop issue with coinbase-adapter

### ISSUE THREAD

**Issue by sgraphics** [Web3Auth/web3auth-web#1967]
### **Describe the bug**

Cannot import coinbase-adapter as es module. Due to error  *"i is not a constructor"*
Apparently coinbase-adapter is doing `import i from "@coinbase/wallet-sdk"` but *"i is not a constructor"*. 

### **To Reproduce**

Reference coinbaseAdapter: [https://unpkg.com/@web3auth/coinbase-adapter@9.0.2/dist/lib.cjs/coinbaseAdapter.js](https://unpkg.com/@web3auth/coinbase-adapter@9.0.2/dist/lib.cjs/coinbaseAdapter.js)

Load the library and call init():
```html
  <script type="module">
    import { CoinbaseAdapter } from "@web3auth/coinbase-adapter";
    const adapter = new CoinbaseAdapter({ clientId : "BPi5PB_UiIZ-cPz1GtV5i1I2iOSOHuimiXBI0e-Oe_u6X3oVAbCiAZOTEBtTXw4tsluTITPqA8zMsfxIKMjiqNQ" }); //taken from https://web3auth.io/docs/sdk/pnp/web/adapters/coinbase#helper-sdks-menu example
    await adapter.init(); //Error here!!
  </script>
```

### **Expected behavior**

No error

### **Additional context**

Issue and potential solution described in more detail here: https://github.com/jspm/project/issues/344#issuecomment-2381061397

Current code:
```js
var CoinbaseWalletSDK = require('@coinbase/wallet-sdk');

// later on

new CoinbaseWalletSDK(...)
```

Should instead be:
```js
var { CoinbaseWalletSDK } = require('@coinbase/wallet-sdk');
```

**Comment by chaitanyapotti** [comment]
Thanks for reporting. will be fixed in 9.2.0 release today
