### ISSUE TITLE
How can I display the external wallet on the mobile terminal and click to pull up the corresponding APP?

### ISSUE THREAD

**Issue by Hicbik** [Web3Auth/web3auth-web#1987]
### **Describe the bug**

External wallet is not displayed on the mobile browser

### **Expected behavior**

Display the wallet and click to call up the corresponding APP

### **Screenshots**

![3c900fa7d03ba1ccedeae10feb43487](https://github.com/user-attachments/assets/9a794087-fcdb-4efa-9f1a-2b3ea0f47215)

### **Device Info (please complete the following information):**

- OS: IOS Android
- Browser chrome
- Version newest
- Web3Auth Version 9.2.3

**Comment by chaitanyapotti** [comment]
You need to add wallet connect adapter or getdefaultadapters
