### ISSUE TITLE
AccountAbstractionProvider does not adhere to Typed Data spec

### ISSUE THREAD

**Issue by jxom** [Web3Auth/web3auth-web#1994]
### **Describe the bug**

Hi! 

I was taking a look through the code for `@web3auth/account-abstraction-provider` and I noticed that it does not adhere to the Typed Data spec for its `eth_signTypedData` handler. Specifically, it [ignores a consumer-passed `primaryType` field](https://github.com/Web3Auth/web3auth-web/blob/master/packages/providers/account-abstraction-provider/src/providers/utils.ts#L195-L205). The `primaryType` field is a [valid (**and required**)](https://eips.ethereum.org/EIPS/eip-712#eth_signtypeddata) parameter for `eth_signTypedData_v4`.

### **Expected behavior**

The `eth_signTypedData` handler should accept a consumer-defined `primaryType`.

### **Additional context**

By modifying the behavior to depend on the consumer `primaryType`, this means that the logic to [infer the `primaryType`](https://github.com/Web3Auth/web3auth-web/blob/master/packages/providers/account-abstraction-provider/src/providers/utils.ts#L189-L196) can be removed. I don't believe this would be a breaking change as consumers (who probably use Viem, Ethers, Web3.js, etc) would be already passing a `primaryType` through. However, if I am wrong, we can definitely add a utility to traverse the DAG and find the `primaryType` in Viem if that is useful. :)

**Comment by chaitanyapotti** [comment]
Hey @jxom, thanks for raising an issue here

We always calculate the primaryType using ethers since we follow the discussion [here](https://github.com/ethers-io/ethers.js/discussions/3614#discussioncomment-4549057)
Right now, our implementation swallows the error if user passes in an incorrect primary type.
We could also throw an error if the DAG derived primaryType doesn't match the user passed one like this

```ts
const { primaryType: primaryTypeFromData } = data as { primaryType?: string };
if (primaryType !== primaryTypeFromData) {
  throw providerErrors.custom({
    message: "DAG calculated primary type and data primary type mismatch",
    code: 4906,
  });
}
```
Would that solve this issue?

**Comment by jxom** [comment]
Viem's `hashTypedData` function should throw for any primary type that is not captured by the `types` schema. It is still valid for a consumer to pass a different primary type to the one that is not at the root of the DAG. Up to you what you want the behavior to be, but I believe the RPC handler should be as close to the EIP-712 spec as possible. I think it would more make sense to enforce the primary type at the application layer instead (which is already the case if the consumer is using Viem, Ethers, Web3.js, etc).

**Comment by tuna1207** [comment]
Hi @jxom , we updated AA provider to allow consumer defined `primaryType` in this [PR](https://github.com/Web3Auth/web3auth-web/pull/1996) viem did throw error when we tried to pass in incorrect `primaryType` but it's this weird one
```
TypeError: Cannot read properties of undefined (reading 'length')
    at bytesToHex (toHex.ts:133:29)
    at toHex (toHex.ts:62:10)
    at encodeField (hashTypedData.ts:250:65)
    at encodeData (hashTypedData.ts:141:27)
    at hashStruct (hashTypedData.ts:114:19)
    at hashTypedData (hashTypedData.ts:77:7)
    at generateSafeMessageMessage (toSafeSmartAccount.ts:481:12)
    at Object.signTypedData (toSafeSmartAccount.ts:1417:34)
    at async Promise.all (:8080/index 1)
    at async Object.signTypedData (toSmartAccount.ts:127:53)
```
I reproduced it here https://stackblitz.com/edit/viem-getting-started-9pzjgg?file=index.ts
could you help check if it's viem's problem in handling `primaryType` error

**Comment by chaitanyapotti** [comment]
Fixed
