### ISSUE TITLE
Cosmos Path Derivation Support on Generated Keys

### ISSUE THREAD

**Issue by demondayza** [Web3Auth/web3auth-web#257]
### **Is your feature request related to a problem? Please describe.**

No related problem.

### **Describe the solution you'd like**

I need a means to set the key derivation path for keys to support the cosmos blockchain. Currently there isnt a obvious means to be able to set a derivation path when generating keys in the auth process. I have no issues with the process as a whole but require some means to set the key derivation or other means to support the cosmos blockchain.

### **Describe alternatives you've considered**

No alternatives available in this context.

**Comment by shahbaz17** [comment]
Hey @demondayza 

Please take a look at this document that explains [how to integrate Web3Auth with the Cosmos Blockchain.](https://web3auth.io/docs/connect-blockchain/cosmos)

If you still need help, please create a topic on [our community forum](https://web3auth.io/community).

**Comment by demondayza** [comment]
Thanks, im sure you will see nice adoption in the cosmos ecosystem going forward.
