### ISSUE TITLE
Libraries not working in Remix.run

### ISSUE THREAD

**Issue by edmbn** [Web3Auth/web3auth-web#369]
### **Describe the bug**

The problem is that the packages are assuming that `process` exists. It doesn't try to import/require it (even though `process` is not a native browser object). The packages typically depend on WebPack bundling these *implicit* modules for you.

So I think the bundling gets confused. Also these packages have side effects in that they execute code simply by importing the module. This was causing the code to access `process` before the proper chunks could be loaded, again, because there's no dependency, so esbuild doesn't know to import the polyfill first.

### **To Reproduce**

1. Create a blank Remix.run app
2. Follow Web3Auth install instructions
3. See error

### **Expected behavior**

Make sure the packages don't expect server code to work without checks or don't expect users to use Webpack to solve this bundle problems.

### **Screenshots**

![image](https://user-images.githubusercontent.com/9108259/182773070-778fa4db-663c-4ccc-8982-0100a7d254fe.png)

### **Device Info (please complete the following information):**

- Device: [e.g. MacBook Pro]
- OS: [e.g. MacOS]
- Web3Auth Version [e.g. 1.1.4]

**Comment by howitworks18** [comment]
im having the same issue, any progress on this?

**Comment by chaitanyapotti** [comment]
I've answered this before but here goes again:
In crypto, we use a lot of elliptic curve packages and most of these are written for node.js and in C++. These libraries are audited by multiple parties and are proven to be reliable.
At Web3Auth, we use these dependencies for crypto operations
The default esm and cjs builds will not be polyfilled for node dependencies and can be polyfilled by the end dapp dev to prevent duplication.

Alternatively, we do provide umd builds with the full polyfills: All packages are available on [jsdelivr](https://cdn.jsdelivr.net/npm/@web3auth/web3auth@0/dist/web3auth.umd.min.js) and [unpkg](https://unpkg.com/@web3auth/web3auth@0/dist/web3auth.umd.min.js) as well

**Comment by chaitanyapotti** [comment]
You can also look at polyfilling for your framework here: https://web3auth.io/docs/troubleshooting/webpack-issues

**Comment by rajat-2024** [comment]
@chaitanyapotti Could you please provide a starter repo for using web3auth with remix js
