### ISSUE TITLE
Sveltekit web3Auth initModal error

### ISSUE THREAD

**Issue by JohnRSim** [Web3Auth/web3auth-web#37]
Added reproducible error here - 
https://github.com/JohnRSim/web3AuthIssue/blob/master/src/routes/index.svelte

When I try to initialise 
```
await web3auth.initModal();
```
I get the following error
![image](https://user-images.githubusercontent.com/364208/151703843-cb3dba55-e2f4-49a1-9f79-c27ad4c69e86.png)

**Comment by JohnRSim** [comment]
Is there a CDN I can use instead if import to test it out with?

**Comment by chaitanyapotti** [comment]
Yes. All packages are available on [jsdelivr](https://cdn.jsdelivr.net/npm/@web3auth/web3auth@0/dist/web3auth.umd.min.js) and [unpkg](https://unpkg.com/@web3auth/web3auth@0/dist/web3auth.umd.min.js) as well

**Comment by Slyracoon23** [comment]
I had a similar issue. I believe it is a polyfill issue. This stackoverflow solved my problem: https://stackoverflow.com/questions/69286329/polyfill-node-os-module-with-vite-rollup-js

**Comment by shahbaz17** [comment]
Hey @Slyracoon23 

Please check this https://web3auth.io/community/t/polyfill-issue-in-svelte-webpack-5-issue/6215

If you still have an issue, please follow up on the community forum link.
