### ISSUE TITLE
Unable call method of contract (Internal JSON-RPC error.)

### ISSUE THREAD

**Issue by gaiverrr** [Web3Auth/web3auth-web#513]
I’m trying to integrate web3auth to existed metamask flow (web3auth flow is separate) but I have error when I try to call contract method: 

UError: Internal JSON-RPC error.

example of usage: 
https://gist.github.com/gaiverrr/f273c7116b7bb316ffac57fad74333e4

When I press Send Transaction button from this example, I have same error
https://github.com/Web3Auth/examples/tree/main/web-modal-sdk/evm/nextjs-evm-web3auth-example

**Comment by himanshuchawla009** [comment]
can you check if any rpc network call is failing, if yes whts is the response of failed rpc call.

**Comment by gaiverrr** [comment]
@himanshuchawla009 I checked getAccounts and getBalance it works nice

**Comment by RodrigoRalhaMoreira** [comment]
Did you manage to fix this issue?

**Comment by oscar88leonardo** [comment]
hi man, i am facing kind of the same issue, i am also getting the Internal JSON_RPC error at  getEthJsonRpcError.

did you find a way to handle this?

**Comment by chaitanyapotti** [comment]
Pls upgrade to the latest version. Shouldn't be an issue anymore
