### ISSUE TITLE
ReactDOM.render is no longer supported in React 18 | vite + react + web3auth

### ISSUE THREAD

**Issue by junhuang-ho** [Web3Auth/web3auth-web#521]
### **Describe the bug**

In the `@web3auth/web3auth` pachakge, running `await web3auth.initModal();` in a vite + react setup leads to error:

> Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17.

### **To Reproduce**

1. Get this repo: `https://github.com/junhuang-ho/minimal-vite-web3-web3auth`
2. cd into repo
3. `yarn install`
4. `yarn run dev`
5. When this line `await web3auth.initModal();` is commented out, no error. When used, leads to error. (line is in `App.tsx`)

### **Expected behavior**

Since the repo is using React 18, changing root like this should solve error:

```
const root = ReactDOM.createRoot(
    document.getElementById('root') as HTMLElement
);
root.render(
    <React.StrictMode>
        <App />
    </React.StrictMode>
)
```

ref: https://stackoverflow.com/questions/71668256/deprecation-notice-reactdom-render-is-no-longer-supported-in-react-18

I already done this in repo but error still persists.

### **Device Info (please complete the following information):**

- Device: Chrome browser: Version 100.0.4896.75 (Official Build) (64-bit)
- Web3Auth Version "^2.0.2"

### **Additional context**

My vite + react setup is based on this repo: https://github.com/himanshuchawla009/web3auth-vite-sample

**Comment by gregoryguillou** [comment]
Same error with NextJS 12.2.5 with ReactJS 18.

**Comment by robport** [comment]
+1

**Comment by root36x9** [comment]
Same error
--
NextJS 12.3.0
ReactJS 18.2.0

**Comment by flbouchut** [comment]
Same error when using this repo : [](https://github.com/Web3Auth/web3auth-web/tree/master/demo/next-app) or `create-next-app`
NextJS 12.3.0 & ReactJS 18.2.0

**Comment by chaitanyapotti** [comment]
This is fixed already in v3 of our sdk. Pls upgrade
