### ISSUE TITLE
Different Wallets: same clientid and same verifier

### ISSUE THREAD

**Issue by andrebruch** [Web3Auth/web3auth-web#550]
A user got a different wallet despite having same clientId, same aggregateVerifier (tkey-auth0-email-passwordless), same verifier (torus) and same verifierId.
He logged in on 6/13/22 and 8/02/22.

The app has been running in production for a few months and the problem has only occurred with one account so far.

**Comment by chaitanyapotti** [comment]
Pls check again. should not be an issue anymore
