### ISSUE TITLE
Outage in Wechat login

### ISSUE THREAD

**Issue by yashovardhan** [Web3Auth/web3auth-web#560]
### Discussed in https://github.com/orgs/Web3Auth/discussions/553

<div type='discussions-op-text'>

<sup>Originally posted by **lordzpipo** September  6, 2022</sup>
Hi, we are testing the web3auth with wechat login, since this morning, after we click wechat login will only getting `something went wrong` error.

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/8167012/188559066-4b463c97-1a56-4deb-9568-455db6ff0979.png">

This is the error track code from this page: `39b7ce25328a78ee96b1`
and also it show this error on the page: `invalid_request: Unknown client: cewDD3i6F1vtHeV1KIbaxUZ8vJQjJZ8V`</div>

**Comment by himanshuchawla009** [comment]
is it outage on our side or auth0?

**Comment by yashovardhan** [comment]
This has been down for weeks now. I think we might like to check our auth0 dashboard atleast for misconfigurations.

**Comment by chaitanyapotti** [comment]
This is fixed now. It was a problem only with testnet
