### ISSUE TITLE
Openlogin Adapter Whitelabeling text colour problem

### ISSUE THREAD

**Issue by yashovardhan** [Web3Auth/web3auth-web#561]
While whitelabeling the openlogin adapter screens, the text colour depends upon the dark/ light mode and not on the colour picked by the user. This results in wierd looking UI in such cases. You can check the screenshots attached in the discussion.

### Discussed in https://github.com/orgs/Web3Auth/discussions/522

<div type='discussions-op-text'>

<sup>Originally posted by **kubrysh** September  1, 2022</sup>
In case when whitelabeling OpenLogin Adapter with options: `dark: true`, and setting the primary color to a light one (e.g. `theme: { primary: '#FFFF00' }`) there are some contrast problems (see attached screenshots).

My suggestion is to implement switching to dark text / icon background when light primary colors are used for whitelabeling OpenLogin Adapter.

<details>
  <summary>Screenshots</summary>

  ![screenshot-1](https://user-images.githubusercontent.com/55651856/187889076-c7e0cfef-3bf9-4a85-8dae-18a0cf9e5e59.jpg)
  ![screenshot-2](https://user-images.githubusercontent.com/55651856/187889107-f232b9ab-76f6-4b7b-b0e9-fc6cc2944f88.jpg)
  ![screenshot-3](https://user-images.githubusercontent.com/55651856/187889581-96b0d62f-109b-4fc8-ba40-d41bed565ca2.jpg)
</details>

</div>

**Comment by chaitanyapotti** [comment]
we've revamped the whitelabel look. pls upgrade to the latest sdk and try again
