### ISSUE TITLE
web3auth torus SSO session is not preserved

### ISSUE THREAD

**Issue by softcheetah** [Web3Auth/web3auth-web#680]
### Discussed in https://github.com/orgs/Web3Auth/discussions/679

<div type='discussions-op-text'>

<sup>Originally posted by **softcheetah** October  5, 2022</sup>
### Steps to reproduce
- Instantiate `@web3auth/core`
- Configure `@web3auth/torus-evm-adapter`
- Initialize Web3Auth
  - `await web3auth.init()`
- Log in using Torus Google SSO
  - `await web3auth.connectTo(WALLET_ADAPTERS.TORUS_EVM)`
- Reload the page
  - Now, it does all initialization steps again.

### Expected behavior
`await web3auth.init()` simply initializes web3auth and torus SSO session is preserved.

### Current behavior
`await web3auth.init()` displays this popup asking me to **login again**.
<img width="480" alt="Screen Shot 2022-10-05 at 10 02 10 AM" src="https://user-images.githubusercontent.com/28793091/194079761-78fa4199-b28c-4fb2-b07d-0c6be5bb8c0e.png">

</div>

**Comment by utopeoninc** [comment]
https://status.web3auth.io/incidents/y5nfm10mcjmc

Switching to cyan instead of testnet fixed it for us.

**Comment by softcheetah** [comment]
@utopeoninc 
This happens on Avalanche Mainnet.

**Comment by chaitanyapotti** [comment]
Torus wallet had session issues. These should be fixed now.
Pls upgrade to the latest version
