### ISSUE TITLE
Metamask option disappears after logout

### ISSUE THREAD

**Issue by florian-niftpad** [Web3Auth/web3auth-web#728]
### **Describe the bug**

The option to connect with Metamask disappears after logout.

### **To Reproduce**

1. Connect with Metamask using `web3auth.connect()`
2. Disconnect using `web3auth.logout()`
3. Try to connect again using `web3auth.connect()`
4. Metamask option is not available

### **Expected behavior**

To be able to connect with Metamask again

### **Device Info**

- Device: Mac
- Browser: Chrome
- Web3Auth Version: 2.1.2

### **Additional context**

`const web3auth = new Web3Auth({
        clientId,
        chainConfig: {
          chainNamespace: CHAIN_NAMESPACES.EIP155,
          chainId: POLYGON_MUMBAI_chainId,
          rpcTarget: POLYGON_MUMBAI_rpcUrl,
        },
      });`

Calling `web3auth.initModal();` on initial page render

After page refresh, the option for Metamask appears again.

**Comment by marianlopezaz** [comment]
same problem here, any solution?

**Comment by chaitanyapotti** [comment]
This should be fixed in the latest version. Pls upgrade

**Comment by franzmoro** [comment]
This is still happening with version 5.1.1
