### ISSUE TITLE
Setting app state in the`web3auth.connectTo` function is not returned post redirect

### ISSUE THREAD

**Issue by kylemantesso** [Web3Auth/web3auth-web#796]
### **Describe the bug**

Setting app state in the`web3auth.connectTo` function is not returned post redirect.

### **To Reproduce**

Call `web3auth.connectTo` with appState

```
web3auth.connectTo(WALLET_ADAPTERS.OPENLOGIN, { ...otherParams, appState: 'some state' });
```

### **Expected behavior**

Expect this to be in the local storage key `openlogin_store` but frankly it isn't clear in the does where it gets stored or how it should be returned.

### **Device Info (please complete the following information):**

    "@web3auth/base": "^2.1.3",
    "@web3auth/core": "^2.1.3",
    "@web3auth/openlogin-adapter": "^2.1.3",
    "@web3auth/web3auth": "^2.1.3",

**Comment by chaitanyapotti** [comment]
Hello, pls upgrade to v7. The appState is present in openlogin state or the idtoken returned after login with web3auth.
