### ISSUE TITLE
`wallet_addEthereumChain` not prompting for metamask 

### ISSUE THREAD

**Issue by Slyracoon23** [Web3Auth/web3auth-web#915]
### **Describe the bug**
``` BUG
const web3auth = new Web3AuthCore({
      clientId: config.web3AuthClientId,
      chainConfig: {
        chainNamespace: CHAIN_NAMESPACES.EIP155,
        chainId: config.chainId,
        rpcTarget: config.rpcUrl,
      },
    });
```
Web3auth does not prompt users to `wallet_addEthereumChain` when connecting with metamask to an previously unknown network.

It may have to do with this
https://github.com/Web3Auth/web3auth-web/blob/acac0ca413f918559296da3ea434345939de199d/packages/adapters/metamask-adapter/src/metamaskAdapter.ts#L146-L163

### **To Reproduce**

1. Install a fresh metamask
2. Instantiate your web3auth  using the following, ( Use avalanche in this case) 
 ```
const web3auth = new Web3AuthCore({
      clientId: config.web3AuthClientId,
      chainConfig: {
        chainNamespace: CHAIN_NAMESPACES.EIP155,
        chainId: config.chainId,
        rpcTarget: config.rpcUrl,
      },
    });
```
4. You won't be prompted `wallet_addEthereumChain` 

### **Expected behavior**

Metmask must prompt `wallet_addEthereumChain` ( in this case Avalanche) 

### **Screenshots**

N.A.

### **Device Info (please complete the following information):**

- Device: Dell g15
- OS: Ubuntu 22
- Browser firefox 106.0.5 
- Version 106.0.5 
- Web3Auth Version 3.0.0

### **Additional context**

Working Solution
If you add `DisplayName` it works
```
  clientId: config.web3AuthClientId,
      chainConfig: {
        displayName: "Avalanche Network C-Chain",
        chainNamespace: CHAIN_NAMESPACES.EIP155,
        chainId: config.chainId,
        rpcTarget: config.rpcUrl,
      },
    });
```

**Comment by chaitanyapotti** [comment]
Will be fixed with 4.0.0 release
Thanks for reporting
