### ISSUE TITLE
Could not validate redirect

### ISSUE THREAD

**Issue by billtlee** [Web3Auth/web3auth-web#916]
### **Describe the bug**

Integration was working and all of a sudden stopped.  Getting the Could not validate redirect please whitelist your domain error but the domain is already on the whitelist.  Currently only happening on our testnet environments.

### **To Reproduce**

Here is our integration code:

```
import { Web3Auth } from "@web3auth/web3auth";
import { CHAIN_NAMESPACES } from "@web3auth/base";

    const web3auth = new Web3Auth({
      chainConfig: {
        chainId: process.env.NEXT_PUBLIC_WEB3AUTH_CHAINID,
        chainNamespace: CHAIN_NAMESPACES.OTHER,
      },
      clientId: process.env.NEXT_PUBLIC_WEB3AUTH_CLIENTID,
    });

await web3auth.initModal();
```
We are using:
    "@web3auth/web3auth": "^1.0.0",

### **Expected behavior**

Should work

### **Screenshots**

![screenshot-2022-11-22-at-10160_112hy32](https://user-images.githubusercontent.com/14323281/203211506-72e097ae-69e8-4b44-90ad-65ca830b03ae.png)

![screenshot-2022-11-22-at-10164_jvhank](https://user-images.githubusercontent.com/14323281/203211521-063a0546-c8c5-4941-aa26-dac85b298627.png)

### **Device Info (please complete the following information):**

- OS: OSX
- Browser Chrome
- Version Version 107.0.5304.110 (Official Build) (x86_64)
- Web3Auth Version 1.0.0

**Comment by hitoshi5858** [comment]
i have the same error.

**Comment by hitoshi5858** [comment]
I explicitly specified a test net and it resolved the issue. If I don't explicitly specify it, it seems to become the main net.

**Comment by billtlee** [comment]
Can you share how you specify the testnet?

**Comment by b0jun** [comment]
> Can you share how you specify the testnet?

@billtlee  you just need to insert this code. 
(before initModal) 
```
const openloginAdapter = new OpenloginAdapter({
    adapterSettings: {
        clientId,
        network: 'testnet',
        uxMode: 'popup'
     }
});
web3auth.configureAdapter(openloginAdapter);

**Comment by chaitanyapotti** [comment]
Pls update to latest sdk and set network: 'testnet'
