### ISSUE TITLE
"View more options" is not consistent with design

### ISSUE THREAD

**Issue by VinaySagarN** [Web3Auth/web3auth-web#93]
UI issue in modal under https://demo-app.web3auth.io/

View more options is not consistent with the design.
https://demo-app.web3auth.io/

![image](https://user-images.githubusercontent.com/90750562/159405559-d89b0ab3-713a-40d2-aad8-1fbbf8276e23.png)

**Comment by himanshuchawla009** [comment]
@lionellbriones can we do this?

**Comment by shahbaz17** [comment]
The issue has been resolved in the most recent SDK version.
