### ISSUE TITLE
Wallet private key is stored as plain text in browser's local storage?

### ISSUE THREAD

**Issue by haowang1013** [Web3Auth/web3auth-web#932]
### **Describe the bug**

When using @web3auth/modal with email login, it seems that the entire private key of the wallet is stored as plain text in browser's local store. This shouldn't be the correct behavior as the documentation says only 1 of the 3 shares is stored locally, right?

### **To Reproduce**

1. Create a simple react app, add @web3auth/modal as dependency and login.
2. Check the browser's local storage.

### **Expected behavior**

The entire private key should not be stored locally.

### **Screenshots
![image](https://user-images.githubusercontent.com/7006155/203880806-859ef6ab-d09a-4bc8-8cfe-0bcfe8a3d0b7.png)
**

**Comment by haowang1013** [comment]
Note that I know it's the entire private key of the wallet because if I do
```
const wallet = new ethers.Wallet(<private key saved in local storage>)
console.log(wallet.getAddress())
```

It is exactly the same as the address I get from the sdk.
(left = address from the sdk, right = address from the stored private key)

![image](https://user-images.githubusercontent.com/7006155/203881471-fa7e2468-c9e8-4158-a678-68d4c516212e.png)

**Comment by mdr-altdev** [comment]
Has this issue been analyzed by the Web3auth devs?
This looks like a pretty important security issue, and I also reproduced what haowang1013 reported.

It makes sense that the private key must be stored somewhere for web3auth to be able to make txs without a browser extension, but could there be a better option than plain text?

**Comment by BiffBish** [comment]
This also happens if you use `@web3auth/base`,`@web3auth/core`,`@web3auth/openlogin-adapter`

**Comment by BiffBish** [comment]
Thanks so much! Awesome work

**Comment by bvand** [comment]
With the key removed from local storage, where will it be stored on the browser side generally (without using the upcoming mpc solution)?
Looking at something like this: https://auth0.com/blog/secure-browser-storage-the-facts - is Web3Auth's storage resilient to XSS? Are there plans to move to a web worker if not already implemented?

**Comment by chaitanyapotti** [comment]
It is currently encrypted with your sessionID and stored in memory or session server

**Comment by chaitanyapotti** [comment]
> Hey Guys, thanks for raising this issue. Although the key is present in openlogin's domain scope rather than in the app's domain, we understand that this can be a security concern when the user has some malicious extensions in the browser. So we have removed it from the store. This fix is already merged to our testing branch which can be seen at https://testing.openlogin.com, we will soon merge it to prod in our upcoming release. Also on long term, we won't need to reconstruct private key at all with our upcoming mpc solution which is currently in alpha. Feel free to try the alpha solution here: https://web3auth.io/mpc.html

This is in prod
