### ISSUE TITLE
web3auth Core logout does not clear openlogin_store in localstorage

### ISSUE THREAD

**Issue by ieow** [Web3Auth/web3auth-web#936]
### **To Reproduce**

1. Go to https://w3a.link/firebase-react-example
2. Click on login then click on logout

### **Expected behavior**
the openlogin_store item  localstorage should be cleared (idToken is in there)

### **Screenshots**
![image](https://user-images.githubusercontent.com/4881057/203920552-4aec4009-2eaf-4513-856e-a319948bd3ca.png)

Screenshots of console logs are welcome

### **Device Info (please complete the following information):**

- Web3Auth Version [e.g. 1.0.0]

**Comment by himanshuchawla009** [comment]
this has been fixed in latest version, all critical fields are cleared on logout now.
