### ISSUE TITLE
ERROR: Web3Auth suddenly stopped working: OpenLogin - RPC Error

### ISSUE THREAD

**Issue by pat-mw** [Web3Auth/web3auth-web#942]
### Discussed in https://github.com/orgs/Web3Auth/discussions/940

<div type='discussions-op-text'>

<sup>Originally posted by **pat-mw** November 25, 2022</sup>
Hi there,

I have a user-facing app which I was hoping to launch today, but last night, all of a sudden - the web3auth stopped working.

Upon further inspection I can see the following error is being thrown:
```
OpenLogin - RPC Error: could not validate redirect, please whitelist your domain: https://wtdkwg2aml4pyi2a.anvil.app for provided clientId BIEreSmO4.... at https://dashboard.web3auth.io
```
<img width="728" alt="Screenshot 2022-11-25 at 11 56 23" src="https://user-images.githubusercontent.com/67635701/203981170-a9f7c771-166d-47de-89f0-0b780ba93fc9.png">

However, this does not make sense as the domain is indeed already whitelisted for this clientId. I have tried removing it and adding it again to the whitelist but no luck.

<img width="959" alt="Screenshot 2022-11-25 at 11 58 16" src="https://user-images.githubusercontent.com/67635701/203981474-2c523e79-aafa-41a9-9316-c2c98e54e674.png">

I'm pretty certain this is not something on my end, as I haven't changed anything. It was working one moment and then it wasn't the next. However, any advice on how I may be able to debug this further would be appreciated.

I don't think this is related but sometimes after the above error, the following error is also thrown:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/67635701/203982360-aff9d6ec-3aa2-444b-be8a-2f037c88a941.png">

Best,

Pat</div>

**Comment by stepheljobs** [comment]
Hi I have the same error just now.. i followed the same scenario with Pat but no luck.

**Comment by pat-mw** [comment]
Hmmm so it's a problem with the test net? That's weird cuz I tried in a blank project on a different domain and it worked with the same rpc URL for the test net @stepheljobs
