### ISSUE TITLE
Ticker is not passed to metamask on addEthereumChain

### ISSUE THREAD

**Issue by rekeye** [Web3Auth/web3auth-web#961]
### **Describe the bug**

While adding the `Polygon Mumbai Testnet` to `Metamask` via the `@web3auth/metamask-adapter` the ticker described in chainConfig of either web3auth instance or metamask adapter itself is not passed to the `wallet_addEthereumChain` call. 

### **To Reproduce**

1. Install fresh metamask
2. Initiate the web3auth instance
    ```ts
    const web3auth = new Web3AuthCore({
        clientId,
        chainConfig: {
          chainNamespace: CHAIN_NAMESPACES.EIP155,
          chainId: MUMBAI_chainId,
          rpcTarget: MUMBAI_rpcTarget,
       }
      });
    ```
3. Configure the metamask adapter
    ```ts
      const adapter = new MetamaskAdapter({
        clientId,
      });
      web3auth.configureAdapter(adapter);
    ```
4. Attempt to connect with metamask adapter
5. Should see a prompt to add the chain
6. Currency symbol is `UNKNOWN` - expected `MATIC`

### **Expected behavior**

Currency symbol should be `MATIC`

### **Screenshots**

Metamask
![image](https://user-images.githubusercontent.com/61563734/204503181-dd362367-66bb-4d9b-9301-17bafc8aa3f4.png)

Web3auth instance chainConfig
![image](https://user-images.githubusercontent.com/61563734/204506505-e5e0f124-330e-49b2-951e-e47b9627789d.png)

### **Device Info (please complete the following information):**

- Device: Dell Latitude 7480
- OS: Ubuntu 21.04
- Browser: Firefox
- Version: 107.0
- Web3Auth Version 3.2.0

### **Additional context**

While researching the issue came across a [possible cause](https://github.com/Web3Auth/web3auth-web/blob/acac0ca413f918559296da3ea434345939de199d/packages/adapters/metamask-adapter/src/metamaskAdapter.ts#L158), this param might be missing
```ts
params: {
  ...
  nativeCurrency:
    {
        name: chainConfig.tickerName,
        symbol: chainConfig.ticker,
        decimals: decimals
    },
}
```

**Comment by chaitanyapotti** [comment]
This will be released with 4.0.0
